### ISSUE TITLE
Add custom filed (for example for cluster name) to Slack report message

### ISSUE THREAD

**Issue by cherez0ff** [fjogeleit/policy-reporter#187]
We using kyverno in several k8s clusters, and all fails info goes to one slack channel. But message does not have info in which cluster issue was generated. And no way to add it, except by changing source code. Please add 'custom message'-like value in config, so it will be added to slack message
For example:

```yaml
slack:
  webhook: "https://hooks.slack.com/services/..."
  minimumPriority: "critical"
  skipExistingOnStartup: true
  custom_message: "Generated in kube1.localhost.lo cluster" # does not exist by default, omitted in slack message if empty
  sources:
  - kyverno
```

**Comment by fjogeleit** [comment]
Would also a map of additional key value pairs okay that will added to the fields like the policy rule namespace etc.

like

```yaml
customFields:
  cluster: Playground
```

**Comment by fjogeleit** [comment]
I added customFields to the slack output as proposed:

```yaml
slack:
  webhook: https://hooks.slack.com/services/T0XXXXX/XXXX/XXXXX
  sources: ['Kyverno']
  customFields:
    cluster: Staging Cluster
  minimumPriority: "warning"
  skipExistingOnStartup: true
```

I will release it in the upcoming days
