### ISSUE TITLE
Can we configure ui rootpath ?

### ISSUE THREAD

**Issue by eddycharly** [fjogeleit/policy-reporter#214]
Hi,
Is this possible to configure the UI rootpath ?
It is useful to run behind a proxy under a specific path (https://xxxx.yyy/prolicy-reporter)

**Comment by fjogeleit** [comment]
Can be closed right?

The solution was an ingress config like:

```yaml
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: \$1\$2
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^(/policy-reporter)$ \$1/ redirect;
    enabled: true
    hosts:
      - host: ~
        paths:
          - path: /policy-reporter(/|$)(.*)
            pathType: Prefix
```
