### ISSUE TITLE
customFields with elastic does not seem to work

### ISSUE THREAD

**Issue by cherez0ff** [fjogeleit/policy-reporter#217]
Hi. I can't enable customFields for elasticsearch.

I used policy-reporter-2.13.2
Below is a part of values for elasticsearch and for slack, and messages sent to them. Elastic message does not contain a custom field, but Slack message does.

I double-checked that same config values are in k8s, and version of deployed pod is ghcr.io/kyverno/policy-reporter:2.10.1

```yaml
elasticsearch:
  certificate: '/var/tmp/cacert.crt'
  customFields:
    - cluster: 'cluster1'
  host: "***"
  index: "sec-kyverno"
  username: "***"
  password: "***"
  rotation: "daily"
  minimumPriority: "warning"
  skipExistingOnStartup: true
slack:
  webhook: "***"
  customFields:
    - cluster: 'cluster1'
  minimumPriority: "warning"
  skipExistingOnStartup: true
```

```json
{
  "_index": "sec-kyverno-2022.10.25",
  "_type": "event",
  "_id": "4fW1DoQBY5GgZkUiFVgc",
  "_version": 1,
  "_score": null,
  "_source": {
    "Message": "Running as root is not allowed. The fields spec.securityContext.runAsUser, spec.containers[*].securityContext.runAsUser, spec.initContainers[*].securityContext.runAsUser, and spec.ephemeralContainers[*].securityContext.runAsUser must be  set to a number greater than zero ",
    "Policy": "require-no-container-root",
    "Rule": "no-run-as-root-user",
    "Status": "fail",
    "Severity": "high",
    "Category": "Pod Security Standards (Restricted)",
    "Source": "Kyverno Event",
    "Timestamp": "2022-10-25T10:36:57Z",
    "Properties": {
      "eventName": "require-no-container-root.172144711e9ed465",
      "time": "2022-10-25T10:36:57Z"
    },
    "Resource": {
      "APIVersion": "",
      "Kind": "Pod",
      "Name": "test3-1337",
      "Namespace": "1337",
      "UID": ""
    },
    "Priority": "error",
    "Scored": false
  },
  "fields": {
    "Timestamp": [
      "2022-10-25T10:36:57.000Z"
    ]
  },
  "sort": [
    1666694217000
  ]
}
```
![image](https://user-images.githubusercontent.com/63862323/197752085-f56756e3-3a51-4ee5-984d-2b25a6c93185.png)
