### ISSUE TITLE
customFields for kinesis not work

### ISSUE THREAD

**Issue by mirtov-alexey** [fjogeleit/policy-reporter#219]
Hello!
Seems like customFields for kinesis not work. I tested it on my cluster with settings like this:

```
kinesis:
  accessKeyID: 
  secretAccessKey:  
  secretRef: ""
  region: ru-central1
  endpoint: 
  streamName: reports
  minimumPriority: ""
  skipExistingOnStartup: true
  customFields:
    cluster-id: test-cluster888888888
```

```
helm install policy-reporter policy-reporter/policy-reporter \
..
--set target.kinesis.customFields.cluster-id="test-cluster888888888" \
..
```

and i dont see this custom fields in target event 

```
{
    "Category": "Pod Security Standards (Baseline)",
    "Message": "validation rule 'adding-capabilities' passed.",
    "Policy": "disallow-capabilities",
    "Priority": "info",
    "Properties": {},
    "Resource": {
        "APIVersion": "v1",
        "Kind": "Pod",
        "Name": "pod2",
        "Namespace": "default",
        "UID": "2d6d8482-008b-43fe-9d7a-5e51b9708abd"
    },
    "Rule": "adding-capabilities",
    "Scored": true,
    "Severity": "medium",
    "Source": "Kyverno",
    "Status": "pass",
    "Timestamp": "2022-10-27T10:23:19Z"
}
```
my college find that from the config this setting is not transferred to the sender
https://github.com/kyverno/policy-reporter/commit/573a1108c7891e7f34146123775451b8b0f67787

https://github.com/kyverno/policy-reporter/blob/a3c09d08222554429ddb6c33d05df4cc36b88cf7/pkg/config/target_factory.go#L634

maybe someone from your team will be able to complete this function?
