### ISSUE TITLE
[UI] Policy Reporter UI V2

### ISSUE THREAD

**Issue by fjogeleit** [fjogeleit/policy-reporter#222]
Rewrite Policy Reporter UI based on modern frontend stack

* Upgrade from VueJS 2 to VueJS 3
* Upgrade from NuxtJS 2 to NuxtJS 3
* Upgrade from Vuetify 2 to Vuetify 3
* Switch from Webpack to Vite

**Improved structure for PolicyReportResults**

Ideas:

* Resolve splitting between PolicyReport and ClusterPolicyReport pages
  * Create Pages based on sources [Kyverno, Falco, Kube Bench, etc...]
  * Splitt between Categories (?)

* New subpages for a single resource with all available information from different sources
* Timeline charts for Logs page

**Comment by fjogeleit** [comment]
@sherifkayad I am working on a new Policy Reporter UI v2 feature called "Custom Boards". Its a way to configure customized dashboards based on filter like namespace selector, polr labels or sources:


https://github.com/kyverno/policy-reporter/assets/16627596/f68c92c6-cf79-4052-99ab-bc05333f4c5d

```yaml

customBoards:
  - name: Team A
    namespaces:
      selector:
        team: team-a
    sources:
      list:
        - kyverno

  - name: Team B
    sources:
      list:
        - trivy configaudit
    namespaces:
      list:
        - trivy-system
    policyReports:
      selector:
        app: adapter
```

<img width="1617" alt="Bildschirmfoto 2023-12-21 um 15 00 39" src="https://github.com/kyverno/policy-reporter/assets/16627596/083e2a34-2d6f-40ec-be1a-b8db8170937a">


Would this be a better solution as the current approach with the custom filter selection based on labels?

**Comment by sherifkayad** [comment]
@fjogeleit I really really apologize for not seeing your comment at all! .. it has been a very long time since I upgraded the policy reporter beyond our last conversation like a year ago or so. I think what you have implemented there (at least as per the video) looks real awesome. If you want I can try to give it a spin soon. Is there anything I can help with at this stage?

**Comment by fjogeleit** [comment]
Hey, no problem. I would like to get your feedback as always.

There are also some new presentations about the new UI

https://www.youtube.com/watch?v=OgFFYKkpEjs
https://www.youtube.com/watch?v=IpGjBJHlAMw

The new docs are available here:

https://kyverno.github.io/policy-reporter-docs/

I am preparing the first release candidate right now, so nothing special. Would already help when you try it out and provide some feedback. If you have any question feel free to contact me.

**Comment by ArjonBu** [comment]
@fjogeleit I am testing this and I see that it's not possible to use wildcards like the following case

```
  customBoards:
    - name: workloads
      namespaces:
        selector:
          workload: "*"
```

Is it trivial to support using wildcards?

**Comment by fjogeleit** [comment]
I will take a look on this

**Comment by fjogeleit** [comment]
I added support for:

```yaml
  customBoards:
  - name: Team A
    namespaces:
      selector:
        team: team-a  # equal
        workload: *    # label exists
        infra: !*           # label does not exist
        env: "dev,test"  # label value is one of [dev, test]
```

In the latest RC release.

Partial wildcards / matching is not supported by the K8s API, e.g. `workload: "w1-*"`
