### ISSUE TITLE
S3 Target error logs 

### ISSUE THREAD

**Issue by mirsafari** [fjogeleit/policy-reporter#269]
Hi. I'm using `policy-reporter:2.13.0` on K8S version `v1.23.14-gke.1800`. I've configured the exports to GCS buckets in the following way:
```yaml
target:
  s3:
    secretRef: "policy-reporter-s3-export-access"
    region: "europe-west"
    endpoint: "https://storage.googleapis.com/"
    bucket: "kyverno-logs"
    pathStyle: false
    minimumPriority: "warning"
    sources: [ kyverno ]
    skipExistingOnStartup: true
    channels:
    - bucket: "kyverno-logs"
      filter:
        status:
          include: ["fail"]
```
I can see the reports in the S3 bucket and they are exported successfully. However, the `policy-reporter` pod is constantly reporting:
```
2023/03/09 11:48:00 [ERROR] S3 : S3 Upload error AccessDenied: Access denied.
        status code: 403, request id: , host id:  
2023/03/09 11:48:00 [ERROR] S3 : S3 Upload error AccessDenied: Access denied.
        status code: 403, request id: , host id: 
```
and is spamming those logs all the time. It is weird because I can see the policy export in S3.

**Comment by fjogeleit** [comment]
So you say that the export to S3 is in general working and you have the logs in your GCP bucket but you still get this error logs?

**Comment by fjogeleit** [comment]
Do you still have issues? Or can I close your issue?

**Comment by mirsafari** [comment]
Sorry for the late response, I didn't receive the notification that you wrote a comment.
Yes, that is exactly the case. I can see the exports in GCS, but the pod is listing those log messages all the time.

**Comment by fjogeleit** [comment]
Hm the error comes directly from the S3 aws Client. So not sure if GCS support might need more special configuration. My thoughts would be to add an GCP/GCS target and use official GCS client.

I can do an implementation in the next days and provide you a dev build to test it.

**Comment by mirsafari** [comment]
That would be awesome. I can do testing and come back with feedback once the dev build is done. 
If there is anything else I can help you with or you need more information/configuration, feel free to ask.

**Comment by fjogeleit** [comment]
Thank you, I will see how the SDK works and if I encounter issues or questions I will reach out to you.

**Comment by fjogeleit** [comment]
I tested the new implementation and it worked so far,

the configuration for you would be look like:

```yaml
target:
  gcs:
    secretRef: "policy-reporter-s3-export-access"
    bucket: "kyverno-logs"
    minimumPriority: "warning"
    sources: [ kyverno ]
    skipExistingOnStartup: true
    filter:
      status:
        include: ["fail"]
```

You basically need only to specify the `bucket` and your secret needs a `credentials` item with the credentials as JSON.

To test it without the helm chart changes is a bit annoying. So I already tested it on GCP. 

I will release it soon, so you will also be able to try it.

**Comment by mirsafari** [comment]
Awesome. Thanks for the fast response. I'm going to watch for the release and test it ASAP

**Comment by fjogeleit** [comment]
I prepared most stuff today. So I think the release will be tomorrow

**Comment by fjogeleit** [comment]
I released the new version with the GCS target.

You can find the possible configurations in the docs: https://kyverno.github.io/policy-reporter/core/targets#google-cloud-storage

As described you basically needs to define the bucket and the credentials (also possible as secretRef)

**Comment by mirsafari** [comment]
I tested it, and I get this weird error. The `values.yml` contains:
```
target:
  gcs:
    secretRef: "policy-reporter-s3-export-access"
    bucket: "kyverno-logs"
    minimumPriority: "warning"
    sources: [ kyverno ]
    skipExistingOnStartup: true
    channels:
    - bucket: "kyverno-logs"
      filter:
        status:
          include: ["fail"]
```
The secret `policy-reporter-s3-export-access` has:
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: policy-reporter
  name: policy-reporter-s3-export-access
  namespace: kyverno
data:
  credentials: "JSON of the SA with write access to the bucket"
```
When I check the logs I can see:
```
1.6794982849362812e+09  error   Google Cloud Storage: Upload error      {"error": "googleapi: Error 403: kyverno-logs@gcp-project.iam.gserviceaccount.com does not have storage.objects.delete access to the Google Cloud Storage object., forbidden"}
```
The docs state that:
```
credentials as JSON string for authentication with the required write permissions for the selected bucket
```
so I'm not sure why `storage.objects.delete` is needed. The SA has `Storage Object Creator` -> permissions https://cloud.google.com/storage/docs/access-control/iam-roles. Maybe this was the cause for the error when using S3 integration as well.
