### ISSUE TITLE
[Helm Chart / GKE] Network Policy enabled - Probes failing

### ISSUE THREAD

**Issue by chichi13** [fjogeleit/policy-reporter#279]
I've installed Policy Reporter in my cluster with Helm.

Here is my `values.yaml` : 

```yaml
resources:
  limits:
    memory: 100Mi
  requests:
    memory: 100Mi
    cpu: 10m

global:
  namespace: "policy-reporter"

nodeSelector:
  node_pool: infra

networkPolicy:
  enabled: true
```

When I apply this configuration I got the following error : 

```bash
Warning  Unhealthy  4s (x11 over 52s)  kubelet            Readiness probe failed: Get "http://10.102.0.15:8080/healthz": dial tcp 10.102.0.15:8080: connect: connection refused
Warning  Unhealthy  4s (x5 over 44s)   kubelet            Liveness probe failed: Get "http://10.102.0.15:8080/ready": dial tcp 10.102.0.15:8080: connect: connection refused
```

When I disable `networkPolicy` there is no problem.

**Specs :**
- GKE 1.24.9
- Policy Reporter 2.13.0
- Helm Chart version 2.17.0

Is this an intended behaviour?

**Comment by fjogeleit** [comment]
Hey, what is the port of your API server?

it allows as default 6443 port to reach your api server. In some cases, depending on the provider this port differs. In some cases it’s then e.g.  443

if so you have to override the egress rules:

https://kyverno.github.io/policy-reporter/guide/helm-chart-core#enable-networkpolicy

**Comment by chichi13** [comment]
You're totally right. Didn't see that, on GKE the port is 443, so I changed the value to : 

```yaml
networkPolicy:
  enabled: true
  egress:
  - to:
    ports:
    - protocol: TCP
      port: 443
```

I've updated the title to specify GKE.

Thanks for your answer :)
