### ISSUE TITLE
Support IRSA for AWS resources

### ISSUE THREAD

**Issue by nlamirault** [fjogeleit/policy-reporter#308]
To use AWS resources like Kinesis, Security Hub, ..., we must set AWS credentials:

```yaml
# AWS access key
accessKeyID: ""
# AWS secret access key
secretAccessKey: ""
```

A better option is to configure IAM roles for service accounts (IRSA). This would be an interesting feature
