### ISSUE TITLE
UI "Logs" to the left disappears in a multi environment setup

### ISSUE THREAD

**Issue by ybelMekk** [fjogeleit/policy-reporter#310]
I configured policy-reporter in my multi cluster.

I use the default setup from the official helm-charts, so the chart is configured with:
```yaml
 ui:
    enabled: true
    clusterName: my cluster
    clusters: [ 
     - name: my other
        api: http:// 
        kyvernoApi: http://
     ]
    networkPolicy:
      enabled: true
    ingress:
      enabled: true
      className: my-ingress
    views:
      dashboard:
        policyReports: true
        clusterPolicyReports: true
      logs: true
      policyReports: true
      clusterPolicyReports: true
      kyvernoPolicies: true
      kyvernoVerifyImages: true
```

When switching from "main" cluster to another  in the UI notice that the "Logs" in the meny to the left disappears, is this intended or do i miss out in some configuration?

Thanks

Youssef
