### ISSUE TITLE
Querying logs in Grafana Loki

### ISSUE THREAD

**Issue by Pavaningithub** [fjogeleit/policy-reporter#313]
Configured kyverno policy reporter to send logs to Grafana cloud Loki stack.

Below is the configuration of Loki.
I'm able to access the logs using [Policy Reporter UI](https://kyverno.github.io/policy-reporter/guide/helm-chart-core#policy-reporter-ui)

```yaml
loki:
  host: "https://<username>:<APIkey>@logs-xxxx.grafana.net"
  path: "/loki/api/v1/push"
  minimumPriority: "debug"
  skipExistingOnStartup: false # tried with true too
  sources: []
```

The logs of the `kyverno-policy-reporter` pod shows the Push to Loki is successful, but I'm unable to view the logs in the Grafana explore.

![image](https://github.com/kyverno/policy-reporter/assets/58260359/aefbc1cf-8e36-45ab-9e28-b32f4607b244)

Querying `{source="policy-reporter"}` in Grafana Logs explore show `No logs found`. tried with `{source="kyverno-policy-reporter"}` but still the same.

![image](https://github.com/kyverno/policy-reporter/assets/58260359/bfbd565e-7004-4d42-8d02-ee672c7e6028)

**Comment by fjogeleit** [comment]
hey, did you try to not override the path and use the default API?

**Comment by Pavaningithub** [comment]
> hey, did you try to not override the path and use the default API?

Yes, I tried below.

```yaml
        loki:
          host: "https://<username>:<APIkey>@logs-xxxx.grafana.net/loki/api/v1/push"
          minimumPriority: "debug"
          skipExistingOnStartup: true
          sources: []
```
It gives me.

```bash
Loki: PUSH FAILED       {"statusCode": 404, "body": "404 page not found\n"}
```

![image](https://github.com/kyverno/policy-reporter/assets/58260359/446afc9a-1519-4133-8b1c-1d72ac469ffa)

**Comment by Pavaningithub** [comment]
> hey, did you try to not override the path and use the default API?

Hey thanks. this worked.

```yaml
        loki:
          host: "https://<username>:<APIkey>@logs-xxxx.grafana.net"
          minimumPriority: "debug"
          skipExistingOnStartup: true
          sources: []
```
