### ISSUE TITLE
Helm chart - incorrect ingress backend configuration

### ISSUE THREAD

**Issue by edgarkz** [fjogeleit/policy-reporter#320]
Hello,
Trying to setup an ingress for the ui using the latest helm (2.19.2) chart however the default definition of ingress modifies the backend value to **kyverno-ui-policy-reporter** service endpoint instead of **kyverno-ui** service. 
to check - i've manually port forwarded both services but only **kyverno-ui** actually shown the ui.

```
service:
  name: kyverno-ui-policy-reporter
  port:
   number: 8080
```

helm chart definition:
```
         ui:
          enabled: "true"
          plugins:
            kuverno: "true"
        kyvernoPlugin:
          enabled: "true"    
        metrics:
          enabled: "true"
        ingress:
          enabled: true
          hosts:
            - host: xxxxx
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kyverno-ui
                    port:
                      number: 8080
          annotations: 
            kubernetes.io/ingress.class: alb
```

**Comment by fjogeleit** [comment]
hey, I will have a look on it this week.

**Comment by fjogeleit** [comment]
Hey, sorry for the late response. To be able to reproduce your issue.

What release name do you use?
Did you configure any overwrites like `global.fullnameOverride`?

**Comment by edgarkz** [comment]
Hi @fjogeleit 
no global overrides were used.
Im syncing the helm chart with argocd using the following config:

  project: system
  source:
    chart: policy-reporter
    helm:
      values: |-
         xxxxxxx - from the above issue
    repoURL: https://kyverno.github.io/policy-reporter
    targetRevision: 2.19.2

**Comment by fjogeleit** [comment]
okay, thanks. Will try to reproduce it.

**Comment by fjogeleit** [comment]
Whats the `source.helm.releaseName` you are using?

**Comment by edgarkz** [comment]
In argocd by default -  the Helm release name is equal to the Application name to which it belongs.
So in my case it would be: **kyverno-ui**

**Comment by fjogeleit** [comment]
okay, thanks

**Comment by fjogeleit** [comment]
@edgarkz you want to create an ingress for the UI right? Then your configuration is wrong, ingress has to be under `ui`. Your configuration creates an ingress for the Core API.

And your hosts config only needs `host`, `paths[].path` and `paths[].pathType`. Backend config is generated automatically.

Like:

```yaml
        ui:
          enabled: true
          plugins:
            kyverno: true
          ingress:
            enabled: true
            hosts:
            - host: chart-example.local
              paths:
                - path: /(.*)
                  pathType: ImplementationSpecific
```

You can also check https://kyverno.github.io/policy-reporter/guide/helm-chart-core#ingress-1 for details.
