### ISSUE TITLE
ingress rules are on same line as tls config

### ISSUE THREAD

**Issue by bakito** [fjogeleit/policy-reporter#323]
since v2.19.3 incress reources do not work, as the rules are on the same line as tls hosts.

```yaml
tls:
    - hosts:
        - foo.bar.comrules: null
```
This is due to the `{{- end -}}`  introduced in #317
