### ISSUE TITLE
[CORE] Auth for policy-reporter API

### ISSUE THREAD

**Issue by yuriydzobak** [fjogeleit/policy-reporter#336]
Hi,
I'm using policy reporter in centralisation entry point. [This feature](https://github.com/kyverno/policy-reporter/blob/8fa2237dec6399dde902cd3cd2b065c67f7c8868/charts/policy-reporter/charts/ui/values.yaml#L42-L52)
Would be nice if policy-reporter has auth method, for example, i configure simple HTTP auth and provide secret to auth another policy reporter via API, because at the moment API is opened for everyone in internal network, filtering by IP doesn't help in my case
Thanks

**Comment by fjogeleit** [comment]
Hey, thanks for your request, I will have a look on it when I find some time but it can take a bit.

**Comment by fjogeleit** [comment]
@yuriydzobak I opened a PR for the core app, can you check if the feature set is fine for your use case?

**Comment by fjogeleit** [comment]
Summary:
* You can configure global HTTP BasicAuthentication via Helm:
  * Username/Password can configured directly or as existing secret with `username` / `password` keys
  * The Authentication is applied to REST APIs and metrics of the Core App and KyvernoPlugin (if enabled)
  * The `Authorization` header will be set in the Policy Reporter UI automatically
    * External Cluster configuration also supports `secretRef` where you can set `username` / `password` as well as the API endpoints (`api`, `kyvernoApi`) and ssl configuration (`skipTLS`, `certificate`)
  * If monitoring enabled the basicAuth configuration will also configured on the ServiceMonitor
      * direct configuration will create a dedicated auth secret for ServiceMonitors
      * secretRef will reuse the existing secret for the ServiceMonitor 

```yaml
global:
  basicAuth:
    #username: "username"
    #password: "password"
    secretRef: auth-secret
```

Example external cluster:

```yaml
ui:
  ...
  clusters:
  - name: Minikube
    api: http://policy-reporter:8080
    kyvernoApi: http://policy-reporter-kyverno-plugin:8080
    basicAuth:
      username: user
      password: password
  - name: Secret
    api: http://policy-reporter:8080
    kyvernoApi: http://policy-reporter-kyverno-plugin:8080
    secretRef: auth-secret
  - name: Unauthorized
    api: http://policy-reporter:8080
    kyvernoApi: http://policy-reporter-kyverno-plugin:8080
```
