### ISSUE TITLE
Policy reporter in crashloop (prometheus label inconsistency)

### ISSUE THREAD

**Issue by eloo-abi** [fjogeleit/policy-reporter#367]
Hi there,

sadly i need to report that our policy reporter instances are in crashloop since a few days (maybe related to an update of kyverno or the policy reporter).

We get the following error in the logs

```
1.7005558788959928e+09	info	UI configured
1.7005558788964608e+09	info	sqlite connection created
1.7005558789128137e+09	info	REST api enabled
1.7005558789128468e+09	info	metrics enabled
1.7005558789130282e+09	info	start client	{"worker": 5}
1.7005558790136192e+09	info	informer sync completed
panic: inconsistent label cardinality: expected 6 label values but got 0 in prometheus.Labels{}

goroutine 3941 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(...)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/gauge.go:250
github.com/kyverno/policy-reporter/pkg/listener/metrics.decreaseOrDelete(0xc0004a82b8, 0xc0015acf00?, 0x0)
	/app/pkg/listener/metrics/result_custom.go:74 +0x12b
github.com/kyverno/policy-reporter/pkg/listener/metrics.CreateCustomResultMetricsListener.func1({0x2?, {0x2aca430?, 0xc0015a7080?}})
	/app/pkg/listener/metrics/result_custom.go:63 +0x657
github.com/kyverno/policy-reporter/pkg/listener.NewMetricsListener.func1({0xc000bd2fb0?, {0x2aca430?, 0xc0015a7080?}})
	/app/pkg/listener/metrics.go:32 +0x9b
github.com/kyverno/policy-reporter/pkg/report.(*lifecycleEventPublisher).Publish.func1(0xc000bd2fd0?, {0x95b605?, {0x2aca430?, 0xc0015a7080?}})
	/app/pkg/report/publisher.go:44 +0x33
created by github.com/kyverno/policy-reporter/pkg/report.(*lifecycleEventPublisher).Publish in goroutine 117
	/app/pkg/report/publisher.go:43 +0xb4
```

our helm chart values are looking like this

```
# Prometheus Metrics API
metrics:
  enabled: true
  mode: simple # available modes are detailed, simple and custom
  customLabels: [] # only used for custom mode. Supported fields are: ["namespace", "rule", "policy", "report" // PolicyReport name, "kind" // resource kind, "name" // resource name, "status", "severity", "category", "source"]
#  filter:
#    sources:
#      exclude: ["Trivy CIS Kube Bench"]
#    status:
#      exclude: ["pass", "skip"]

# enable policy-report-ui
ui:
  enabled: true

  # possible default displayModes: light/dark
  displayMode: "dark"

  # default refreshInterval, set 0 to disable it
  refreshInterval: 10000

  # Key/value pairs that are attached to all resources.
  annotations: {}

  log:
    # holds the latest 200 validation results in the UI Log
    size: 200

  # enable/disable views as needed in the Policy Reporter UI
  # disabled log view will also disable the UI as push target
  views:
    dashboard:
      policyReports: true
      clusterPolicyReports: true
    logs: true
    policyReports: true
    clusterPolicyReports: true
    kyvernoPolicies: true
    kyvernoVerifyImages: true

  plugins:
    kyverno: true

  # configurations related to the PolicyReporter API
  policyReporter:
    port: 8080

  # configurations related to the RolicyReporter KyvernoPlugin API
  kyvernoPlugin:
    port: 8080

  imagePullSecrets: []

  replicaCount: 1

  deploymentStrategy: {}
    # rollingUpdate:
    #  maxSurge: 25%
    #  maxUnavailable: 25%
    # type: RollingUpdate

  resources:
    limits:
      memory: 100Mi
      cpu: 50m
    requests:
      memory: 50Mi
      cpu: 10m

kyvernoPlugin:
  enabled: true
  metrics:
    enabled: false
  blockReports:
    # enable the feature
    enabled: false
    # namespace where kyverno events are created
    eventNamespace: default
    results:
      # maximal results stored in a PolicyReport per namespace
      maxPerReport: 200
      # keep only the latest result of the same violation in the report
      keepOnlyLatest: false
    # source used for the PolicyReportResults
    source: "Kyverno Event"

# Settings for the monitoring subchart
monitoring:
  enabled: true

global:
  # available plugins
  plugins:
    # enable kyverno for Policy Reporter UI and monitoring
    kyverno: false
  # The name of service policy-report. Defaults to ReleaseName.
  backend: ""
  # overwrite the fullname of all resources including subcharts
  fullnameOverride: ""
  # configure the namespace of all resources including subcharts
  namespace: ""
  # additional labels added on each resource
  labels: {}

emailReports:
  clusterName: "" # (optional) - displayed in the email report if configured
  smtp:
    secret: "" # (optional) secret name to provide the complete or partial SMTP configuration
    host: ""
    port: 465
    username: ""
    password: ""
    from: "" # displayed from email address
    encryption: "" # default is none, supports ssl/tls and starttls

  # basic summary report
  summary:
    enabled: false
    schedule: "0 8 * * *" # CronJob schedule defines when the report will be send
    activeDeadlineSeconds: 300 # timeout in seconds
    backoffLimit: 3 # retry counter
    ttlSecondsAfterFinished: 0
    restartPolicy: Never # pod restart policy

    to: [] # list of receiver email addresses
    filter: {} # optional filters
    #  disableClusterReports: false # remove ClusterPolicyResults from Reports
    #  namespaces:
    #    include: []
    #    exclude: []
    #  sources:
    #    include: []
    #    exclude: []
    channels: [] # (optional) channels can be used to to send only a subset of namespaces / sources to dedicated email addresses    channels: [] # (optional) channels can be used to to send only a subset of namespaces / sources to dedicated email addresses
    #  - to: ['team-a@company.org']
    #    filter:
    #      disableClusterReports: true
    #      namespaces:
    #        include: ['team-a-*']
    #      sources:
    #        include: ['Kyverno']
  # violation summary report
  violations:
    enabled: false
    schedule: "0 8 * * *" # CronJob schedule defines when the report will be send
    activeDeadlineSeconds: 300 # timeout in seconds
    backoffLimit: 3 # retry counter
    ttlSecondsAfterFinished: 0
    restartPolicy: Never # pod restart policy

    to: [] # list of receiver email addresses
    filter: {} # optional filters
    #  disableClusterReports: false # remove ClusterPolicyResults from Reports
    #  namespaces:
    #    include: []
    #    exclude: []
    #  sources:
    #    include: []
    #    exclude: []
    channels: [] # (optional) channels can be used to to send only a subset of namespaces / sources to dedicated email addresses    channels: [] # (optional) channels can be used to to send only a subset of namespaces / sources to dedicated email addresses
    #  - to: ['team-a@company.org']
    #    filter:
    #      disableClusterReports: true
    #      namespaces:
    #        include: ['team-a-*']
    #      sources:
    #        include: ['Kyverno']

# Supported targets for new PolicyReport Results
target:
  loki:
    # loki host address
    host: ""
    # path to your custom certificate
    # can be added under extraVolumes
    certificate: ""
    # skip TLS verification if necessary
    skipTLS: false
    # receive the host from an existing secret instead
    secretRef: ""
    # loki api path, defaults to "/api/prom/push" (deprecated)
    path: ""
    # minimum priority "" < info < warning < critical < error
    minimumPriority: ""
    # list of sources which should send to loki
    sources: []
    # Skip already existing PolicyReportResults on startup
    skipExistingOnStartup: true
    # Added as additional labels to each Loki event
    customLabels: {}
    # Filter Results which should send to this target by namespaces, priorities or policies
    # Wildcars for namespaces and policies are supported, you can either define exclude or include values
    # Filters are available for all targets except the UI
    filter: {}
    #      namespaces:
    #        include: ["develop"]
    #      priorities:
    #        exclude: ["debug", "info", "error"]
    channels: []
  #    - host: "http://loki.loki-stack:3100"
  #      sources: []
  #      customLabels: {}
  #      filter:
  #        namespaces:
  #          include: ["develop"]
  #        priorities:
  #          exclude: ["debug", "info", "error"]

  slack:
    # slack app webhook address
    webhook: ""
    # receive the webhook from an existing secret instead
    secretRef: ""
    # minimum priority "" < info < warning < critical < error
    minimumPriority: ""
    # list of sources which should send to slack
    sources: []
    # Skip already existing PolicyReportResults on startup
    skipExistingOnStartup: true
    # Added as additional fields to each Slack event
    customField: {}
    # filter results send by namespaces, policies and priorities
    filter: {}
    # add additional slack channels with different configurations and filters
    channels: []
  #    - webhook: "https://slack.webhook1"
  #      filter:
  #        namespaces:
  #          include: ["develop"]
  #        priorities:
  #          exclude: ["debug", "info", "error"]
  #        policies:
  #          include: ["require-run-as-nonroot"]
  #    - webhook: "https://slack.webhook2"
  #      minimumPriority: "warning"
  #      filter:
  #        namespaces:
  #          include: ["team-a-*"]

  ui:
    # path to your custom certificate
    # can be added under extraVolumes
    certificate: ""
    # skip TLS verification if necessary
    skipTLS: false
    # minimum priority "" < info < warning < critical < error
    minimumPriority: "warning"
    # list of sources which should send to the UI Log
    sources:
      - kyverno
    # Skip already existing PolicyReportResults on startup
    skipExistingOnStartup: true

  webhook:
    # webhook host address
    host: ""
    # path to your custom certificate
    # can be added under extraVolumes
    certificate: ""
    # skip TLS verification if necessary
    skipTLS: false
    # receive the host and/or token from an existing secret, the token is added as Authorization header
    secretRef: ""
    # additional http headers
    headers: {}
    # minimum priority "" < info < warning < critical < error
    minimumPriority: ""
    # list of sources which should send to the UI Log
    sources: []
    # Skip already existing PolicyReportResults on startup
    skipExistingOnStartup: true
    # filter results send by namespaces, policies and priorities
    filter: {}
    # add additional webhook channels with different configurations and filters
    channels: []
```

and the following versions of kyverno components are running:

```
ghcr.io/kyverno/kyverno:v1.11.0                        
ghcr.io/kyverno/background-controller:v1.11.0          
ghcr.io/kyverno/cleanup-controller:v1.11.0             
ghcr.io/kyverno/policy-reporter:2.17.2                 
ghcr.io/kyverno/policy-reporter-kyverno-plugin:1.6.1   
ghcr.io/kyverno/policy-reporter-ui:1.9.1               
ghcr.io/kyverno/reports-controller:v1.11.0 
```

Maybe this is already known? Or do you have any idea what could be the case?

I have already tried to delete all reports in our cluster this does also not help :(
