### ISSUE TITLE
No email sent to channel

### ISSUE THREAD

**Issue by sudoleg** [fjogeleit/policy-reporter#408]
Hey, 

I configured the policy-reporter to send summary reports via email. This works perfectly fine for the 'global' summary report, which gets sent to the email specified under `emailReports.summary.to`. 

I used the same email in a channel, where I include only specific namespaces. For some reason, there is no email sent, although there are multiple PolicyReports in the specified namespaces with failed results. 

The helm values look like this:
```yaml
  emailReports:
    clusterName: "hcp-int" # (optional) - displayed in the email report if configured
    titlePrefix: "Policies Report for HCP int" # title prefix in the email subject
    smtp:
      secret: "smtp-configuration" # (optional) secret name to provide the complete or partial SMTP configuration

    # basic summary report
    summary:
      enabled: true
      schedule: "*/5 * * * *" # CronJob schedule defines when the report will be send
      activeDeadlineSeconds: 300 # timeout in seconds
      backoffLimit: 3 # retry counter
      ttlSecondsAfterFinished: 0
      restartPolicy: Never # pod restart policy

      to: ["email@domain.com"] # list of receiver email addresses
      filter: {} # optional filters
      #  disableClusterReports: false # remove ClusterPolicyResults from Reports
      #  namespaces:
      #    include: []
      #    exclude: []
      #  sources:
      #    include: []
      #    exclude: []
      channels:
      - to: ["email@domain.com"]
        filter:
          disableClusterReports: true
          namespaces:
            include: ["utilities", "trivy-system", "common"]
          sources:
            include: ["Trivy*"]
```

Any idea what might be going wrong?

**Comment by fjogeleit** [comment]
Hey @sudoleg, currently the `sources` filter doesn't support wildcards.

**Comment by sudoleg** [comment]
Ah ok... I don't quite understand how to specify PolicyReports that were generated by trivy-polr-adapter as source. Can you help me?

**Comment by fjogeleit** [comment]
the adapter produces multiple sources as listed in the readme:

https://github.com/fjogeleit/trivy-operator-polr-adapter?tab=readme-ov-file#available-sources

So you need to specify each source you are interested in like: `['Trivy ConfigAudit', 'Trivy Vulnerability']`

**Comment by sudoleg** [comment]
It works now, thank you very much @fjogeleit 

One more suggestion: As wildcards are not supported, I would adjust the documentation:
- https://github.com/kyverno/policy-reporter-docs/blob/main/content/02.%20core/email-reports.md?plain=1#L191
- https://github.com/kyverno/policy-reporter-docs/blob/main/content/02.%20core/email-reports.md?plain=1#L229
- https://github.com/kyverno/policy-reporter-docs/blob/main/content/02.%20core/email-reports.md?plain=1#L183 (if wildcards aren't supported for namespaces as well)

I find it quite confusing. If you agree, I would adjust the docs :)

**Comment by fjogeleit** [comment]
Yes, you're right. This should be fixed for sources. Maybe I will add support for wildcards but until then the docs should fixed.

Namespaces should have support for wildcards, did you try it?

**Comment by sudoleg** [comment]
No, I didn't try wildcards with namespaces, as I don't have a usecase for that. I will leave the docs for namespaces as it is and adjust it for sources

**Comment by anuragjain08** [comment]
Hi @sudoleg @fjogeleit 

Could you pls help me with emailReport configuration , my values.yaml config looks like below, and it is not even showing any logs or anything for email/smtp. Am I missing something here?

                

 
```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: kyverno
spec:
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      version: 2.24.1
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace

  upgrade:
    crds: CreateReplace
  
  values:
    kyvernoPlugin:
      enabled: true
      podLabels:
        aa: bb
        cc: dd
        ee: ff
    ui:
      enabled: true
      plugins:
        kyverno: true
      ingress:
        className: alb
        enabled: true
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/ssl-redirect: "443"
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:aaa:certificate/bbb-ccc-ddd-bf36-fff
          alb.ingress.kubernetes.io/healthcheck-path: /
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
          alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=aaa-bb-cc-alb-logs
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/security-groups: sg-aa,sg-bb,sg-cc
          alb.ingress.kubernetes.io/subnets:  subnet-aa,subnet-bb,subnet-cc,subnet-dd,subnet-ee,subnet-ff
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
          alb.ingress.kubernetes.io/success-codes: "200,303,301"
          alb.ingress.kubernetes.io/target-type: ip
        hosts:
          - host: kyverno.dev.aa.net
            paths:
              - path: "/*"
                pathType: ImplementationSpecific
      podLabels:
        aa: bb
        cc: dd
        ee: ff
    podLabels:
      aa: bb
      cc: dd
      ee: ff
    target:
      slack:
        minimumPriority: "warning"
        skipExistingOnStartup: true
        channels:
        - webhook: "https://hooks.slack.com/services/aa/bb/cc"
          filter:
            namespaces:
              include: ["test"]
    #envFromSecret: kyverno-smtp-creds
    envVars:
      - name: SMTP_USERNAME
        valueFrom:
          secretKeyRef:
            name: kyverno-smtp-creds
            key: kyverno_smtp_username
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kyverno-smtp-creds
            key: kyverno_smtp_password
    logging:
      encoding: console # possible encodings are console and json
      logLevel: 1 # default info
      development: true # more human readable structure, enables stacktraces and removes log sampling
```

    api:
      logging: true # enable debug API access logging, sets logLevel to debug
    emailReports:
      # -- (optional) - Displayed in the email report if configured
      clusterName: "dev-v4"
      # -- Title prefix in the email subject
      titlePrefix: "Report"
      # -- Resource constraints for the created CronJobs
      resources: {}
      smtp:
        # -- (optional) Secret reference to provide the complete or partial SMTP configuration
        secret: ""
        # -- SMTP Server Host
        host: "email-smtp.us-east-1.amazonaws.com"
        # -- SMTP Server Port
        port: 587
        # -- SMTP Username
        username: "${SMTP_USERNAME}"
        # -- SMTP Password
        password:"${SMTP_PASSWORD}"
        # -- Displayed from email address
        from: "test@test.com"
        # -- SMTP Encryption
        # Default is none, supports ssl/tls and starttls
        encryption: ""
        # -- Skip SMTP TLS verification
        skipTLS: true
        # -- SMTP Server Certificate file path
        certificate: ""

      summary:
        # -- Enable Summary E-Mail reports
        enabled: true
        # -- CronJob schedule
        schedule: "* * * * *"
        # -- CronJob activeDeadlineSeconds
        activeDeadlineSeconds: 300
        # -- CronJob backoffLimit
        backoffLimit: 3
        # -- CronJob ttlSecondsAfterFinished
        ttlSecondsAfterFinished: 0
        # -- CronJob restartPolicy
        restartPolicy: Never
        # -- List of receiver email addresses
        to: ["test@test.com"]
        # -- (optional) Report filter
        filter: {}
        #  # remove ClusterPolicyResults from Reports
        #  disableClusterReports: false
        #  namespaces:
        #    include: []
        #    exclude: []
        #  sources:
        #    include: []
        #    exclude: []
        # -- (optional) Channels can be used to to send only a subset of namespaces / sources to dedicated email addresses
        channels:
          - to: ['test@test.com']
            filter:
              disableClusterReports: true
              namespaces:
                include: ['dev']
              sources:
                include: ['Kyverno']

      violations:
        # -- Enable Violation Summary E-Mail reports
        enabled: true
        # -- CronJob schedule
        schedule: "* * * * *"
        # -- CronJob activeDeadlineSeconds
        activeDeadlineSeconds: 300
        # -- CronJob backoffLimit
        backoffLimit: 3
        # -- CronJob ttlSecondsAfterFinished
        ttlSecondsAfterFinished: 0
        # -- CronJob restartPolicy
        restartPolicy: Never
        # -- List of receiver email addresses
        to: ["test@test.com"]
        # -- (optional) Report filter
        filter: {}
        #  disableClusterReports: false # remove ClusterPolicyResults from Reports
        #  namespaces:
        #    include: []
        #    exclude: []
        #  sources:
        #    include: []
        #    exclude: []
        # -- (optional) Channels can be used to to send only a subset of namespaces / sources to dedicated email addresses
        channels: []
          - to: ['test@test.com']
            filter:
              disableClusterReports: true
              namespaces:
                include: ['dev']
              sources:
                include: ['Kyverno']``


        Could you pls suggest if I am missing something here?
        Thank you
        Anurag Jain

**Comment by fjogeleit** [comment]
channels: []
      - to: ['test@test.com']
      
This per Looks Like invalid yaml to me

**Comment by anuragjain08** [comment]
Thank you for your prompt response @fjogeleit and sorry for getting back so late on this. I was checking the indentation issues and it was related to that only.

I am still struggling with secrets part of it.

I have below ExternalSecrets created stored in AWS parameter store and this yaml is working as expected, as I checked the values with echo & decode command to verify:

`apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kyverno-smtp-creds
  namespace: kyverno
spec:
  refreshInterval: 1m  
  secretStoreRef:
    kind: ClusterSecretStore
    name: parameter-store  
  target:
    name: kyverno-smtp-creds
    creationPolicy: Owner  
  data:
    - secretKey: kyverno_smtp_username
      remoteRef:
        key: /dev/kyverno/username
    - secretKey: kyverno_smtp_password
      remoteRef:
        key: /dev/kyverno/password`
        
     
   and it is showing my secrets as well with correct values.
   
   But when I am trying to consume it in my helm chart its not picking up these values. Though I am using secrets in similar manner in other helm chart and its working fine there.
   
   `    envVars:
      - name: SMTP_USERNAME
        valueFrom:
          secretKeyRef:
            name: kyverno-smtp-creds
            key: kyverno_smtp_username
      - name: SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kyverno-smtp-creds
            key: kyverno_smtp_password
    logging:
      encoding: console
      logLevel: 1
      development: true
    api:
      logging: true
    emailReports:
      clusterName: dev-v4
      titlePrefix: Report
      resources: {}
      smtp:
        secret: ''
        host: email-smtp.us-east-1.amazonaws.com
        port: 465
        username: '${SMTP_USERNAME }'
        password: '${SMTP_PASSWORD }'
        from: aa@test.com
        encryption: 'ssl/tls'
        skipTLS: false
        certificate: ''
    `
   
   When I am passing plain text username and password in helm chart its working as expected. so anything which I may be missing here?
   
   Kind Regards
   Anurag Jain

**Comment by fjogeleit** [comment]
```go
	_ = v.BindEnv("emailReports.smtp.username", "EMAIL_REPORTS_SMTP_USERNAME")
	_ = v.BindEnv("emailReports.smtp.password", "EMAIL_REPORTS_SMTP_PASSWORD")
	_ = v.BindEnv("emailReports.smtp.encryption", "EMAIL_REPORTS_SMTP_ENCRYPTION")
	_ = v.BindEnv("emailReports.smtp.host", "EMAIL_REPORTS_SMTP_HOST")
	_ = v.BindEnv("emailReports.smtp.port", "EMAIL_REPORTS_SMTP_PORT")
	_ = v.BindEnv("emailReports.smtp.from", "EMAIL_REPORTS_SMTP_FROM")
```

are the correct env var keys.

**Comment by anuragjain08** [comment]
okay and 
`username: '${EMAIL_REPORTS_SMTP_USERNAME }' 
password: '${EMAIL_REPORTS_SMTP_PASSWORD }'`

is this the correct way of referencing it ?

**Comment by fjogeleit** [comment]
should be, yes

**Comment by fjogeleit** [comment]
What you mean with referencing? Do you want to set them as env vars in the deployment or use a secret ref?

**Comment by anuragjain08** [comment]
I mean I have declared it as env variable as secreRef

`envVars:
      - name: EMAIL_REPORTS_SMTP_USERNAME
        valueFrom:
          secretKeyRef:
            name: kyverno-smtp-creds
            key: kyverno_smtp_username
      - name: EMAIL_REPORTS_SMTP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kyverno-smtp-creds
            key: kyverno_smtp_password`
            
   And now I want to consume these env variables for my username and password and I tried it as below 
   
   `username: '${EMAIL_REPORTS_SMTP_USERNAME}'
        password: '${EMAIL_REPORTS_SMTP_PASSWORD}'`
        

        
  and it is not working as expected.

**Comment by anuragjain08** [comment]
` username: '{{ .Values.envVars.EMAIL_REPORTS_SMTP_USERNAME }}'

        password: '{{ .Values.envVars.EMAIL_REPORTS_SMTP_PASSWORD }}'`
        
       

@fjogeleit  tried with this as well but its not working as expected.

**Comment by fjogeleit** [comment]
I don't what you want to do.

You can:

1. provide SMT config directly in the values.yaml (https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L224)
2. add them as ENV vars in the deployment (https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L836)
3. use a secret ref which requires an existing Secret with defined keys (https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/values.yaml#L226 / https://kyverno.github.io/policy-reporter-docs/policy-reporter/email-reports.html)

everything else does not relate to the project itself rather then your setup/deployment tooling.

**Comment by anuragjain08** [comment]
@fjogeleit  I think we both are trying to say same thing just that I am trying to do with the second option envVars.

What I am trying to say is I have my envVars for username and password in values.yaml as below , since I can't expose username and password directly in values.yaml file as well. I have a secret where they are stored and then I am referecing those secrets as secrteref in envVars and then trying to consume those envVars in username and password

`   envVars:

      - name: EMAIL_REPORTS_SMTP_USERNAME
      
        valueFrom:
        
          secretKeyRef:
          
            name: kyverno-smtp-creds
            
            key: kyverno_smtp_username
            
      - name: EMAIL_REPORTS_SMTP_PASSWORD
      
        valueFrom:
        
          secretKeyRef:
          
            name: kyverno-smtp-creds
            
            key: kyverno_smtp_password
            `
            
           
And then I am consuming these envVars in my username and password from values.yaml in my deployment.yaml as below:

`emailReports:

      clusterName: dev-v4

      titlePrefix: Report

      resources: {}

      smtp:

        secret: ''

        host: email-smtp.us-east-1.amazonaws.com

        port: 465

        #username: ''

        #password: ''

        username: '{{ .values.envVars.EMAIL_REPORTS_SMTP_USERNAME }}'

        password: '{{ .values.envVars.EMAIL_REPORTS_SMTP_PASSWORD }}'

        from: aa@bb.com

        encryption: 'ssl/tls'

        skipTLS: false

        certificate: ''`
  
 so is this not the correct way here?
  
or do you have any example where the secrets are defined in some parameter store or aws secret manager and consumed in policy-reporter helm chart?
  
 I just hope I am bit clear now to explain the scenario. 
  
  Thank you

**Comment by fjogeleit** [comment]
If you use envVars you don’t set anything in the emailreport values. Env Cars only picked up when the related values are empty.

**Comment by anuragjain08** [comment]
I have tried that option as well @fjogeleit  but its not picking up.

Infact tried with plain text secrets as well where I am passing my username and password in envVars as below but its not picking it up.
```
envVars:
     EMAIL_REPORTS_SMTP_USERNAME: "abcdefghi"
     EMAIL_REPORTS_SMTP_PASSWORD: "aaaa+bbb56744"
```
     
and then left the emailreport values blank as below:

```
emailReports:
      clusterName: dev-v4
      titlePrefix: Report
      resources: {}
      smtp:
        secret: ''
        host: email-smtp.us-east-1.amazonaws.com
        port: 465
        username: ''
        password: ''
```
     
  and tried another option as well with just below emailreport values as well :
  
```
 emailReports:
      clusterName: dev-v4
      titlePrefix: Report
      resources: {}
      smtp:
        secret: ''
        host: email-smtp.us-east-1.amazonaws.com
        port: 465
        #username: ''
        #password: ''
```


But username and password is not getting picked up from envVars. Initially I thought that it was some issue with my secretRef but its not working with plaintext as well.


**NOTE: but when I am passing the same plain text username and password in emailReports values its working as expected and I am receiving emails, which rules out the condition that credentials are incorrect**

```
emailReports:
      clusterName: dev-v4
      titlePrefix: Report
      resources: {}
      smtp:
        secret: ''
        host: email-smtp.us-east-1.amazonaws.com
        port: 465
        username: 'abcdefghi'
        password: 'aaaa+bbb56744'
```
