### ISSUE TITLE
Problem with sending messages to Telegram

### ISSUE THREAD

**Issue by F-Fx** [fjogeleit/policy-reporter#418]
Hello, pls help with configuration Telegram target.

I installed police-reporter

```
helm install policy-reporter policy-reporter/policy-reporter --set monitoring.enabled=true --set monitoring.grafana.namespace=monitoring --set monitoring.serviceMonitor.labels.release=monitoring --set telegram.token="XXXXXXXXX" --set telegram.chatID="XXXXXXXXX" -n sec-kyverno-lp01 --create-namespace
```

I created some pod, which generated policy report, but not messages sent to telegram.
How can i see logs, that policy-reporter try to send message to Telegram (no logs in policy-reporter pod)

I dont know is it normal, but chat-id starts with "-", but i checked it with curl and test messages it`s work

I test my Telegram bot_token and chat_id, by sending test messages to channel by curl.

helm values
```yaml
monitoring:
  enabled: true
  grafana:
    namespace: monitoring
  serviceMonitor:
    labels:
      release: monitoring
telegram:
  chatID: XXXXXXXXX
  token: XXXXXXXXX
```
kyverno:v1.8.5
policy-reporter:2.18.1

**Comment by fonru** [comment]
I test my Telegram bot_token and chat_id, by sending test messages to channel by curl.

**Comment by fonru** [comment]
helm values
```yml
monitoring:
  enabled: true
  grafana:
    namespace: monitoring
  serviceMonitor:
    labels:
      release: monitoring
telegram:
  chatID: XXXXXXXXX
  token: XXXXXXXXX
```
I don`t know is it normal, but chat-id starts with "-", but i checked it with curl and test messages it`s work
