### ISSUE TITLE
Policy Reporter Targets as CRDs

### ISSUE THREAD

**Issue by mveitas** [fjogeleit/policy-reporter#436]
Currently all configuration for targets such as email, slack, etc are all done in a central location. This requires teams make a contribution to the main policy-reporter configuration and deploy the changes.

Creating a CRD that describes a target would allow teams to manage their notifications in a self-service manner. An example below:

```
apiVersion: kyverno.io/v1alpha1
kind: PolicyReporterTarget
spec:
   slack:
      webhook: "https://hooks.slack.com/services/123..."
      skipExistingOnStartup: true
      filter:
         namespaces:
            include: ["team-a-*"]
         priorities:
            exclude: ["info", "debug"]
         policies:
            include: ["require-*"]
```

Centralized configuration of SMTP server configuration would be kept within the core configuration for the Policy Reporter
