### ISSUE TITLE
strange S3 config error when using SecurityHub as target

### ISSUE THREAD

**Issue by balonik** [fjogeleit/policy-reporter#445]
Hi,

I have added AWS SecurityHub into my targets. Now when policy reporter starts there is strange error in output.

```
1.7174164487271972e+09  error   S3.Region has not been declared                <--------
1.7174164487276146e+09  info    SecurityHub configured
1.7174164487276573e+09  info    UI configured
1.717416448815206e+09   info    sqlite connection created
1.717416448835441e+09   info    REST api enabled
1.7174164488359635e+09  info    start client    {"worker": 5}
1.7174164497151537e+09  warn    informers not synced yet, waiting for k8s client to be up
1.7174164499365907e+09  info    informer sync completed
```

`target` section from my `values.yaml`:

```
target:
  ui:
    host: "http://policy-reporter-ui:8080"
    minimumPriority: "warning"
    skipExistingOnStartup: true
    sources:
      - kyverno
  securityHub:
    region: "us-east-1"
    accountID: "266081407098"
    minimumPriority: "critical"
    skipExistingOnStartup: true
    sources:
      - kyverno
```

Policy reporter version:
```
Image:           ghcr.io/kyverno/policy-reporter:2.19.0
Image ID:        ghcr.io/kyverno/policy-reporter@sha256:71c3191e6f245252aa9bc4930a7273d5b75d3afbd8386ff0fab674706fd9fb80
```
