### ISSUE TITLE
Wrong key "label" instead of "labels" in redis mainfest file

### ISSUE THREAD

**Issue by avatar77-pm** [fjogeleit/policy-reporter#466]
Hi.

Error from server (BadRequest): error when creating "./": Pod in version "v1" cannot be handled as a Pod: strict decoding error: unknown field "metadata.label"

policy-reporter/manifest/policy-reporter-kyverno-ui-ha/redis.yaml

```
metadata:
  name: redis
  label:
    app: redis
```
