### ISSUE TITLE
The Secrets do not have the namespace in manifests

### ISSUE THREAD

**Issue by avatar77-pm** [fjogeleit/policy-reporter#467]
Hi.

I found more problems in manifest files. The Secrets create in "default" namespace instead of "policy-reporter" as namespaces are not defined in manifests.

```
---
apiVersion: v1
data:
  config.yaml: dWk6CiAgaG9zdDogaHR0cDovL3BvbGljeS1yZXBvcnRlci11aTo4MDgyCiAgbWluaW11bVByaW9yaXR5OiAid2FybmluZyIKICBza2lwRXhpc3RpbmdPblN0YXJ0dXA6IHRydWUKCnJlZGlzOgogIGVuYWJsZWQ6IHRydWUKICBhZGRyZXNzOiAicmVkaXM6NjM3OSIKICBkYXRhYmFzZTogMQogIH
ByZWZpeDogInBvbGljeS1yZXBvcnRlciIK
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/name: policy-reporter
  name: policy-reporter-config
type: Opaque
---
apiVersion: v1
data:
  config.yaml: YmxvY2tSZXBvcnRzOgogIGVuYWJsZWQ6IHRydWU=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/name: policy-reporter-kyverno-plugin
  name: policy-reporter-kyverno-plugin-config
type: Opaque
---
apiVersion: v1
data:
  config.yaml: cmVkaXM6CiAgZW5hYmxlZDogdHJ1ZQogIGFkZHJlc3M6ICJyZWRpczo2Mzc5IgogIGRhdGFiYXNlOiAxCiAgcHJlZml4OiAicG9saWN5LXJlcG9ydGVyLXVpIgo=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/name: policy-reporter-ui
  name: policy-reporter-ui-config
type: Opaque
---

```
