### ISSUE TITLE
http auth broken

### ISSUE THREAD

**Issue by bkk-bcd** [fjogeleit/policy-reporter#548]
If I define credentials for `basicAuth`, the UI will prompt for login. After logging in the UI fails to render correctly.  It looks like to me the web app isn't using the credentials when making API calls. Not sure though.

```yaml
basicAuth:
  username: admin
  password: my-password
```

![Screenshot 2024-10-30 at 09 55 00](https://github.com/user-attachments/assets/0c30410b-7daf-43a3-9f40-0a79f6cf0074)

![Screenshot 2024-10-30 at 09 56 59](https://github.com/user-attachments/assets/fb5ce764-3ac4-4832-81df-4ce4e451dad8)
