### ISSUE TITLE
Helm chart doesn't properly render PDB 

### ISSUE THREAD

**Issue by ArjonBu** [fjogeleit/policy-reporter#605]
The latest helm chart `3.0.0-rc.10` is not properly rendering the PDB for UI. 
To reproduce, just set the replicaCount to 3.

```
ui:
  enabled: true
  replicaCount: 3
  podDisruptionBudget:
    minAvailable: 1
```

It will return the following error:
`Error: template: policy-reporter/templates/ui/poddisruptionbudget.yaml:15:4: executing "policy-reporter/templates/ui/poddisruptionbudget.yaml" at <include "ui.podDisruptionBudget" .>: error calling include: template: policy-reporter/templates/ui/_helpers.tpl:59:18: executing "ui.podDisruptionBudget" at <.Values.plugin.kyverno.ui.podDisruptionBudget.minAvailable>: nil pointer evaluating interface {}.podDisruptionBudget`
