### ISSUE TITLE
policy reporter service account namespaces cannot be overwritten

### ISSUE THREAD

**Issue by ghost** [fjogeleit/policy-reporter#608]
Which is required if you put service accounts with cluster role bindings in dedicated namespaces

**Comment by fjogeleit** [comment]
What do you mean exactly? The ServiceAccount created by the Helm Chart should have another namespace as the other components?

**Comment by fjogeleit** [comment]
Like for all other components, you can use `namespaceOverride` to set the Namespace for all resources, including the ServiceAccount.

**Comment by ghost** [comment]
Yes, i want only the service account which i create before using this helm chart to be in a different namespace. 
So i have 
```
serviceAccount:
  name: my-service-account
  create: false
  namespace: my-service-account-namespace  <- this is what i need
```
