### ISSUE TITLE
UI Custom Board using namespace label selector not working

### ISSUE THREAD

**Issue by carlos-leocadio-jnpr** [fjogeleit/policy-reporter#611]
I am running Policy Reporter Chart 3.0.0-rc.2 and when I try to configure a UI customBoard using a namespace selector (as shown) below, I end up getting an empty board with the error message "No configured namespaces are found".

Image: policy-reporter-ui:2.0.0-rc.1

```yaml
      customBoards:
        - name: SRE Maintained
          clusterScope:
            enabled: false
          namespaces:
            selector:
              Maintainer: sre
```

Is there any known issue/limitation related with this feature?
