### ISSUE TITLE
helm chart version 3.0.0-rc.12 ServiceMonitor YAML rendering broken

### ISSUE THREAD

**Issue by morremeyer** [fjogeleit/policy-reporter#618]
Hey everyone,

the helm chart version `3.0.0-rc.12` has a YAML rendering issue in at least the ServiceMonitor.

Using the following values as `policy-report-values.yaml`:

```yaml
metrics:
  enabled: true

monitoring:
  enabled: true
  grafana:
    dashboards:
      # We've imported and adjusted the dashboard manually
      enabled: false

livenessProbe:
  timeoutSeconds: 5

readinessProbe:
  timeoutSeconds: 5
```

And then running

```
helm template policy-reporter/policy-reporter --name-template kyverno-policy-reporter --namespace kyverno --kube-version 1.31 --values policy-report-values.yaml --include-crds --version 3.0.0-rc.12 --debug
```

results in

```
Error: YAML parse error on policy-reporter/templates/monitoring/servicemonitor.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context
```

The ServiceMonitor is rendered as

```yaml
# Source: policy-reporter/templates/monitoring/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: policy-reporter-monitoring
  namespace: kyverno
  labels:
    
    helm.sh/chart: policy-reporter-3.0.0-rc.12app.kubernetes.io/name: policy-reporter-monitoring
    app.kubernetes.io/instance: kyverno-policy-reporter
    app.kubernetes.io/version: "3.0.0-rc.7"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
spec:
  selector:
    matchLabels:
        app.kubernetes.io/name: policy-reporter
        app.kubernetes.io/instance: kyverno-policy-reporter
  endpoints:
  - port: http
    honorLabels: false
```

There's a missing newline in the labels.

Thanks for your work, really great to see the progress here!
