### ISSUE TITLE
Can't get openIDConnect to work in 3.0.0-rc.13 and no logs output in UI pods

### ISSUE THREAD

**Issue by sarg3nt** [fjogeleit/policy-reporter#633]
I'm trying to get `openIDConnect` to work in the new `3.0.0-rc.13`.

When I turn it on and configure it, the UI pods crash loop due to the health checks failing.

There are zero log lines being output, which makes debugging this kind of hard.  

Usually I can get OIDC working with enough log reading and head banging and we do have it working in several other apps in our cluster (ArgoCD, Grafana, Oauth2Proxy, Headlamp, etc.)

I've tried changing / removing just about every value I can think of in the `openIDConnect` settings but get the same issue every time.
With `openIDConnect` turned off, the UI works fine, so I know the ingress and everything else is set up correctly.

I did read through: https://github.com/kyverno/policy-reporter/blob/2c98eac298d94cd8d5ef71bb6db16d6c8c82b863/docs/UI_AUTH.md

## Values
This is a subset of the values.
```yaml
  openIDConnect:
    # -- Enable openID Connect authentication
    enabled: true
    # -- OpenID Connect Discovery URL
    discoveryUrl: "${issuer_url}"
    # -- OpenID Connect Callback URL
    callbackUrl: "https://kyverno.${cluster_fqdn}/callback"
    #callbackUrl: http://localhost:8082/callback
    # -- OpenID Connect ClientID
    clientId: "${client_id}"
    # -- OpenID Connect ClientSecret
    clientSecret: "${client_secret}"
    # -- Optional Group Claim to map user groups to the profile
    # groups can be used to define access control for clusters, boards and custom boards.
    groupClaim: "Group.Read.All"
    # -- OpenID Connect allowed Scopes
    scopes: 
      - openid
      - profile
      - email
    # -- Provide OpenID Connect configuration via Secret
    # supported keys: `discoveryUrl`, `clientId`, `clientSecret`
    secretRef: ""
```

I've tried removing the `groupClaim` and the `scopes` with no luck.  I doubt that's it as I don't know why that would cause the issue we are seeing.

## Events:
```
                                                                                                                                                        
  Type     Reason     Age               From               Message                                                                                                            
  ----     ------     ----              ----               -------                                                                                                            
  Normal   Scheduled  27s               default-scheduler  Successfully assigned kyverno-policy-reporter/policy-reporter-ui-5595c9cf7-6nk7d to lpul-vault-k8s-agent-0.vault.ad.selinc.com                                                                                                                                                                   
  Normal   Pulling    27s               kubelet            Pulling image "sel-docker.artifactory.metro.ad.selinc.com/kyverno/policy-reporter-ui:2.0.0-rc.4"                   
  Normal   Pulled     25s               kubelet            Successfully pulled image "sel-docker.artifactory.metro.ad.selinc.com/kyverno/policy-reporter-ui:2.0.0-rc.4" in 2.692s (2.692s including waiting). Image size: 32694854 bytes.                                                                                                                   
  Normal   Created    24s               kubelet            Created container policy-reporter-ui                                                                               
  Normal   Started    24s               kubelet            Started container policy-reporter-ui                                                                               
  Warning  Unhealthy  7s (x4 over 24s)  kubelet            Readiness probe failed: Get "http://192.168.1.94:8080/healthz": dial tcp 192.168.1.94:8080: connect: connection refused                                                                                                                                                                          
  Warning  Unhealthy  7s (x2 over 17s)  kubelet            Liveness probe failed: Get "http://192.168.1.94:8080/healthz": dial tcp 192.168.1.94:8080: connect: connection refused                                                                                                                                                                           
```

## UI Secret
Below has senstaive values redacted and is from a run with no `scopes` or `groupClaim`
```yaml
config.yaml: "namespace: kyverno-policy-reporter\n\ntempDir: /tmp\n\nlogging:\n  api:                                               
  false\n  server: false\n  encoding: console\n  logLevel: 0\n\nserver:\n  port: 8080\n                                             
  \ cors: true\n  overwriteHost: true\n\nui:\n  displayMode: \n  banner: \n\nclusters:\n                                            
  \ - name: Default\n    secretRef: policy-reporter-ui-default-cluster\n\nsources:\n                                                
  \ - name: kyverno\n    chartType: result\n    exceptions: false\n    excludes:\n                                                  
  \     results:\n      - warn\n      - error\nopenIDConnect:\n    callbackUrl: https://kyverno.k8s.vault.ad.selinc.com/callback\n  
  \   clientId: <redacted>\n    clientSecret: <redacted>\n                  
  \   discoveryUrl: https://login.microsoftonline.com/<redacted>/v2.0\n                                   
  \   enabled: true\n    groupClaim: \"\"\n    scopes: []\n    secretRef: \"\"\noauth:\n                                            
  \   callbackUrl: \"\"\n    clientId: \"\"\n    clientSecret: \"\"\n    enabled:                                                   
  false\n    provider: \"\"\n    scopes: []\n    secretRef: \"\"\n"   
```

Let me know if you need to see the rest of the helm `values.yaml` file.

Is this a bug or am I doing something wrong.

**Comment by fjogeleit** [comment]
Will take a Look and see if I can improve logging

**Comment by fjogeleit** [comment]
@sarg3nt do you see no logs at all or no logs related to OpenIDConnect? Represents `Group.Read.All` a nested structure?

**Comment by fjogeleit** [comment]
Can you set the UI image tag (`ui.image.tag`) to `2.0.0-rc.5`?

Your unhealthy error assumes that it is not able to start the server and already fails in the setup process.

Does `kubectl logs deploy/policy-reporter-ui` show anything?

**Comment by sarg3nt** [comment]
@fjogeleit 
Set image tag to `2.0.0-rc.5`, same result.

No, `Group.Read.All` is simply the name of the group claim in our Azure app for some reason.  It's what we have to map from.
So for example in the ArgoCD Dex config I have to set.
```yaml
            scopes:
              - openid
              - profile
              - email
            claimMapping:
              groups: "Group.Read.All"
```

Correct, zero logs whatsoever.
![image](https://github.com/user-attachments/assets/ed9664a1-a31b-4f02-b4b5-df9ef989ade7)

**Comment by fjogeleit** [comment]
Could you set the `ui.logging.logLevel` to `-1`? To show debug logs and check if any debug log occours?

https://kyverno.github.io/policy-reporter-docs/policy-reporter-ui/configuration.html#logging

**Comment by sarg3nt** [comment]
@fjogeleit sorry for the delay.
Tried setting `ui.logging.logLevel` to `-1`, still zero logs in `policy-reporter-ui`

**Comment by fjogeleit** [comment]
Hm not really sure why it shows no logs at all.

I released a new chart version where I added the Readiness and Liveness probes to the UI values. So you could try to disable both by overwrite `ui.livenessProbe` and `ui.readinessProbe`. 

```yaml
ui:
  livenessProbe:
    httpGet: null
    port: null
  readinessProbe:
    httpGet: null
    port: null
```

Hopefully this leads to an actual error and logs in the pod to investigate into.

**Comment by caiobegotti** [comment]
@fjogeleit hi Frank! Is this issue here the only one blocking the final helm chart release for 3.0.0? Out of curiosity since I'm tracking it myself 🙏

**Comment by fjogeleit** [comment]
Hey, I think its not a blocking issue. Just had not much time recently - sorry. I try to release it end of next week.

**Comment by fjogeleit** [comment]
@sarg3nt do you still have issues with the authentication?

**Comment by sarg3nt** [comment]
@fjogeleit Sorry for the delay, been super busy getting some other things fixed.

I've gotten further.  
First thing to note.
```yaml
ui:
  livenessProbe:
    httpGet: null
    port: null
  readinessProbe:
    httpGet: null
    port: null
```
Doesn't work.  It does not validate.
But, I was able to deploy then remove them by editing the deployment.
Once I did that I started to get logs.
Turns out it was our proxy.  I "knew" that, but had put the proxy in the `policy-reporter` deployment but not the `ui` one.

So I'm at the stage where I can at least get it to try but am stuck on a different error.

I have our Azure app set up properly (from what I can tell).  We are using the same app for all the other oauth apps in the cluster so I think it should be good.  I added the callback URL for KPR but it's not working.

I get the login prompt, log in, then am redirected to this error.

```

Looks like there’s a problem with this site

https://kyverno.k8s.vault.ad.selinc.com/callback?code=1.ATgAMB84Ev4QLE6qOl4D6-tZ7IXNkYRRReRPt8zr0Bqzdrs4AEU4AA.AgABBAIAAABVrSpeuWamRam2jAF1XRQEAwDs_wUA9P8rGKz6wvYIZSIN0BWR_ytXU866icEcsl-8ixzS4nUiehZgjni00OfLgkR6LvZ3O-P5MGpGyXUdXON492DC8SZxZllZ1StoOb48XiOPH6CZ_Ol4mIPZCKjv5Nl5rd86mIiv4nly6sKoQVqpMefEWM1vYefrIkeRHblRXdbFccG79cF27ZeJjx0IVKeXWg77-7fyZsHYdM8HnSmvGzX1umrMfhOSvTUEleNk_pW5JUe4ysYqjD8F1QVVSoN4bh7eeieUsFb0axOlkAZQyHysk20zJ36_KKcuMRkJ86YS7Iton2BZwyiRLLFB7nmog4JG1_yj5I9fmEjKyLrCy3Z_5dMG-pAidsWDPgVFBDoZuTvJXPmz0cYW4BKT4FxFhjg-P0ABG8frVY0liICbk_3BgBO2QeGAVhRI0mKokQoZR7-Dcr25zC8xeOrUijpBOs0X4Eq3t_3WpRW-I86cAW00Zsu8b1IPBKRGu6L_ttVqY05ISFwKnxJYuxhu6kjnhgg_2WT3-531yDZmz7W40a8L67YizwsiTbjVX4-Dps8I9GMLmwDM_-Ud92D00AbNffjYeDkslOHBC-b_KbkwsPh0wZX4pRqZkHJ9R_6D8GU_YInCNghepjbtheD0xahycdiAUxxzmjtFrxD_IhLbBxCh1d7a2kNq-GWJhFK5UV-xx41YnfDTg2e6UDGBY0TNIKo5huTJVNASIz-ho5uc5mbbqGaOP-bKhGCzztViDtzpTT0119mkWGPd_FYYI8t8Nr1t7l_70PdeZiGZep7W2GxAUgZHTPo-QDdDVikedRNB5NFprYlptOO7o5kjMIDdquy8zGN2YwguBAyWkOyNi_9vUM9kVrJDKV8cx9zaPGq3mf5_S3dG7hZ9LwXK1ujNU3xdltK61CB3YDycd4M&state=gmQ_iGtnZ0m0p4pyr59gf-02JVPltC7fwNE0Mb1HGLvOqGACgpN7e9xXSLqjVjAvwhN3MB3VjPD-BvVBlZYKaw==&session_state=dcedbd79-1e30-4bc2-9297-a9aabd0791b4 might have a temporary problem or it could have moved.

Error code: 500

    The site could be temporarily unavailable or too busy. Try again in a few moments.
```

The UI pod logs have this.

```
1.7442216413241477e+09  info    auth/router.go:38       setup oauth routes
1.7442216413324945e+09  info    config/resolver.go:172  values loaded from secret       {"secretRef": "policy-reporter-ui-default-cluster"}
1.7442216413325663e+09  info    config/resolver.go:389  register UI     {"path": "/var/run/ko/ui"}
1.744221641332594e+09   info    cmd/run.go:35   Server starts   {"port": 8080}
1.744221661348003e+09   error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_SGFMJ3NC336RK2TEURMVZOSD4MIQVUZ27T342ZTX76TC3FV3JNBA: no such file or directory"}
1.7442216613480601e+09  error   auth/middleware.go:47   profile not found
1.7442216613480692e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_SGFMJ3NC336RK2TEURMVZOSD4MIQVUZ27T342ZTX76TC3FV3JNBA: no such file or directory"}
1.744221665294222e+09   error   auth/handler.go:24      failed to complete user {"error": "could not find a matching session for this request"}
```
The config in the `values.yaml` file

```yaml
  openIDConnect:
    # -- Enable openID Connect authentication
    enabled: true
    # -- OpenID Connect Discovery URL
    discoveryUrl: "${issuer_url}"
    # -- OpenID Connect Callback URL
    callbackUrl: "https://kyverno.${cluster_fqdn}/callback"
    # -- OpenID Connect ClientID
    clientId: "${client_id}"
    # -- OpenID Connect ClientSecret
    clientSecret: "${client_secret}"
    # -- Optional Group Claim to map user groups to the profile
    # groups can be used to define access control for clusters, boards and custom boards.
    groupClaim: "Group.Read.All"
    # -- OpenID Connect allowed Scopes
    scopes: 
      - openid
      - profile
      - email
    # -- Provide OpenID Connect configuration via Secret
    # supported keys: `discoveryUrl`, `clientId`, `clientSecret`
    secretRef: ""
```

I think the callback URL is set up properly as if it is not then I get a different error.
Unless the UI wants a specific callback URL then I don't know what that is.
I'm using 
`"https://kyverno.${cluster_fqdn}/callback"`

Any help would be appreciated.

Edit: We are on latest version of KPR as of yesterday.

Edit2: Is there anything in the ingress we need?  Or something else?

**Comment by fjogeleit** [comment]
thanks for the details, do youse a replica count < 1 for the UI deployment? I recognizied that auth with multiple pods does not work right now because sessions are stored as files in the pods and not shared between them.

**Comment by brilong** [comment]
As a new user of policy-reporter-ui, I am also trying to get this working with boards and clusters restricted by group membership.  I am running chart 3.1.0 and policy-reporter-ui:2.3.2.  OIDC works when I remove the group restrictions.

I enabled logging -1 but do not see any debug logs for group verification, only the profile not found error:
```
1.744227461274165e+09	debug	config/resolver.go:163	create secret client	{"namespace": "policy-reporter"}
1.744227461291198e+09	info	config/resolver.go:172	values loaded from secret	{"secretRef": "policy-reporter-oidc-creds"}
1.7442274612912326e+09	debug	config/resolver.go:264	setup openIDConnect	{"callback": "https://policy-reporter.engineering/callback", "discovery": "https://foo.sso.duosecurity.com/oidc/bar/.well-known/openid-configuration"}
1.744227461521725e+09	info	auth/router.go:38	setup oauth routes
1.744227461528173e+09	debug	server/server.go:60	cluster registered	{"name": "Default", "id": "default"}
1.7442274615281992e+09	info	config/resolver.go:389	register UI	{"path": "/var/run/ko/ui"}
1.7442274615282414e+09	info	cmd/run.go:35	Server starts	{"port": 8080}
2025/04/09 19:43:34 [sessions] ERROR! open /tmp/session_HTWP5WSAXWDHBIA74FW3DZDA7JIL2WHL6PVYQMURT55SFXY26MGQ: no such file or directory
1.7442278142598052e+09	error	auth/middleware.go:120	failed to logout from provider	{"error": "open /tmp/session_BGGU3AXYQPGRQ342U5VOZQCSWSCGCRDDYS3EBO5ZFKEISJK2GLIQ: no such file or directory"}
1.7442278142598636e+09	error	auth/middleware.go:47	profile not found
1.7442278142598763e+09	error	auth/middleware.go:120	failed to logout from provider	{"error": "open /tmp/session_BGGU3AXYQPGRQ342U5VOZQCSWSCGCRDDYS3EBO5ZFKEISJK2GLIQ: no such file or directory"}
2025/04/09 19:43:42 [sessions] ERROR! open /tmp/session_HTWP5WSAXWDHBIA74FW3DZDA7JIL2WHL6PVYQMURT55SFXY26MGQ: no such file or directory
```

My sanitized configuration looks like the following:
```
tempDir: /tmp
logging:
  api: false
  server: false
  encoding: console
  logLevel: -1
server:
  port: 8080
  cors: true
  overwriteHost: true
ui:
  displayMode:
  logo:
    path:
    disabled: false
clusters:
  - accessControl:
      groups:
      - company-devops
    host: http://policy-reporter:8080
    name: Default
boards:
  accessControl:
    groups:
    - company-devops
sources:
  - name: kyverno
    type: result
    exceptions: false
    excludes:
      results:
      - warn
      - error
openIDConnect:
    callbackUrl: https://policy-reporter.engineering/callback
    enabled: true
    groupClaim: memberof
    scopes: openid profile email groups memberof
    secretRef: policy-reporter-oidc-creds
    skipTLS: false
```

FWIW, I'm using this with Cisco Duo SSO (similar to Okta).  When I remove `clusters` and `boards` from the configuration, my coworkers and I can login.  Right now, I am able to log in, but I get an empty screen and just see the hamburger, logo, and banner.  I also seem my OIDC username in the upper right corner.

**Comment by fjogeleit** [comment]
Thanks for your feedback, let me add some debug logs to improve the Integration process

**Comment by sarg3nt** [comment]
@fjogeleit, yeah, we had the replica count set to 2.  Setting it to 1 got me a little bit closer (I think)
It now pauses for a while then we get the 500 error.

Logs from the UI pod

```
1.7442431793327224e+09  info    auth/router.go:38       setup oauth routes
1.7442431793409922e+09  info    config/resolver.go:172  values loaded from secret       {"secretRef": "policy-reporter-ui-default-cluster"}
1.7442431793410578e+09  info    config/resolver.go:389  register UI     {"path": "/var/run/ko/ui"}
1.7442431793410823e+09  info    cmd/run.go:35   Server starts   {"port": 8080}
1.7442434046279392e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_SGFMJ3NC336RK2TEURMVZOSD4MIQVUZ27T342ZTX76TC3FV3JNBA: no such file or directory"}
1.7442434046280587e+09  error   auth/middleware.go:47   profile not found
1.7442434046280658e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_SGFMJ3NC336RK2TEURMVZOSD4MIQVUZ27T342ZTX76TC3FV3JNBA: no such file or directory"}
1.7442434306505554e+09  error   auth/handler.go:24      failed to complete user {"error": "Post \"https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/oauth2/v2.0/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
1.7442434737064345e+09  error   auth/middleware.go:47   profile not found
1.7442434973504972e+09  error   auth/handler.go:24      failed to complete user {"error": "Post \"https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/oauth2/v2.0/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
1.7442434979525094e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_UW5MU3UUD3MPFUHGLXBPLHI3WICIVRJ7SBX2ALEA5WDQT4Z7CABA: no such file or directory"}
1.744243497952552e+09   error   auth/middleware.go:47   profile not found
1.7442434979525585e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_UW5MU3UUD3MPFUHGLXBPLHI3WICIVRJ7SBX2ALEA5WDQT4Z7CABA: no such file or directory"}
1.7442435210115302e+09  error   auth/handler.go:24      failed to complete user {"error": "Post \"https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/oauth2/v2.0/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```

I'm seeing this in the browser logs

![Image](https://github.com/user-attachments/assets/7fae1b3c-db09-4bb6-b20c-2f243004e1f3)

**Comment by fjogeleit** [comment]
Can you try to delete your current Cookie in the Browser?

I need to check the Browser error Message. Will take a Look today

**Comment by fjogeleit** [comment]
@sarg3nt it looks like that your proxy adds an Content Security Policy header which blocks none whitelisted domains from execute inline JS. I assume you need to add the UI to this whitelist to be able to work.

**Comment by fjogeleit** [comment]
@brilong I created a new UI tag with additional logs for group mapping issues and a debug log which roles are assigned to a user. You can set `ui.image.tag` to `2.3.4` to get the new image. Hope this helps to debug your issue. Let me know if you need additional logs/help.

**Comment by sarg3nt** [comment]
Hi @fjogeleit 
Still haven't figured this out.

On 2.3.2 and logging set at `-1` I'm getting this.

```
1.7443225314663584e+09  debug   config/resolver.go:264  setup openIDConnect     {"callback": "https://kyverno.k8s.vault.ad.selinc.com/callback", "discovery": "https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/v2.0/.well-known/openid-configuration"}
1.744322531910172e+09   info    auth/router.go:38       setup oauth routes
1.7443225319147449e+09  debug   config/resolver.go:163  create secret client    {"namespace": "kyverno-policy-reporter"}
1.7443225319182758e+09  info    config/resolver.go:172  values loaded from secret       {"secretRef": "policy-reporter-ui-default-cluster"}
1.7443225319183626e+09  debug   server/server.go:60     cluster registered      {"name": "Default", "id": "default"}
1.7443225319183755e+09  info    config/resolver.go:389  register UI     {"path": "/var/run/ko/ui"}
1.7443225319184108e+09  info    cmd/run.go:35   Server starts   {"port": 8080}
1.7443228941925266e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_FXXNCSK5IFQVSEEYUDY7UPUPC6FIIYXHDAH2CWNUVVIZZNMOUNEQ: no such file or directory"}
1.7443228941926e+09     error   auth/middleware.go:47   profile not found
1.7443228941926076e+09  error   auth/middleware.go:120  failed to logout from provider  {"error": "open /tmp/session_FXXNCSK5IFQVSEEYUDY7UPUPC6FIIYXHDAH2CWNUVVIZZNMOUNEQ: no such file or directory"}
1.7443229186586266e+09  error   auth/handler.go:24      failed to complete user {"error": "Post \"https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/oauth2/v2.0/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```

On 2.3.4 the pod won't start so I have to delete the health checks.  Once I do I get the following, but then the pod crashes anyway.
NOTE: The interesting thing about the logs below is that the error is spit out before I load the page or try to log in.  It's like it's trying to hit the azure login endpoint on startup for some reason.
```
xt deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
1.7443232415724719e+09  error   config/resolver.go:307  failed to setup oidc    {"error": "Get \"https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/v2.0/.well-known/openid-configuration\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
Error: Get "https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/v2.0/.well-known/openid-configuration": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Usage:
  policy-reporter-ui run [flags]

Flags:
  -c, --config string                       target configuration file
      --dev                                 Enable CORS Header for development
  -h, --help                                help for run
      --kube-as string                      Username to impersonate for the operation
      --kube-as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --kube-as-uid string                  UID to impersonate for the operation
      --kube-certificate-authority string   Path to a cert file for the certificate authority
      --kube-client-certificate string      Path to a client certificate file for TLS
      --kube-client-key string              Path to a client key file for TLS
      --kube-cluster string                 The name of the kubeconfig cluster to use
      --kube-context string                 The name of the kubeconfig context to use
      --kube-disable-compression            If true, opt-out of response compression for all requests to the server
      --kube-insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
  -n, --kube-namespace string               If present, the namespace scope for this CLI request
      --kube-password string                Password for basic authentication to the API server
      --kube-proxy-url string               If provided, this URL will be used to connect via proxy
      --kube-request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
      --kube-server string                  The address and port of the Kubernetes API server
      --kube-tls-server-name string         If provided, this name will be used to validate server certificate. If this is not provided, hostname used to contact the server is used.
      --kube-token string                   Bearer token for authentication to the API server
      --kube-user string                    The name of the kubeconfig user to use
      --kube-username string                Username for basic authentication to the API server
      --local                               use kube config to connect to cluster
      --no-ui                               Disable the embedded frontend
      --overwrite-host                      Overwrite Proxy Host and set Forward Header
      --port int                            PolicyReporter UI port (default 8080)

Get "https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/v2.0/.well-known/openid-configuration": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

I've tried a myriad of different options for the OIDC config itself and have had no luck with any of them. 
About the Content Security Policy header, I think that is coming from the Azure oauth2 provider.  I looked into the NGINX ingress config and we have nothing se that would do that.  I tried setting a header to allow it and it didn't do anything.  Note that it does say it is in report only mode, so it's not blocking anything.

**Comment by fjogeleit** [comment]
@sarg3nt the newer image introduced a preconfigured http client for openIDConnect. Maybe the timeouts to short for you, you can go back to the 3.2.2 and I might add more configurations for the client to customize the timers. But the connection seems really slow on your end.

So, I think this JS error does not matter and the real issue is NS_ERROR_NET_ERROR_RESPONSE which should be caused by 

```
1.7442435210115302e+09  error   auth/handler.go:24      failed to complete user {"error": "Post \"https://login.microsoftonline.com/12381f30-10fe-4e2c-aa3a-5e03ebeb59ec/oauth2/v2.0/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```

So over all the bad network connection and response time lead to timeouts and crashing the process. I am not sure how to help with this. Seems to be an issue/configuration problem on your side.

**Comment by sarg3nt** [comment]
@fjogeleit I don't know how it could be a bad network connection or timeout issues. We have several other Oauth2 apps configured in the same cluster to the same endpoint app in Azure and they all work fine and login happens very quickly.
Do you have an example of how this is typically set up with Microsoft EntraID?

**Comment by fjogeleit** [comment]
sorry for the late response, I tested Azure with a basic config like:

```yaml
ui:
  openIDConnect:
    enabled: true
    discoveryUrl: https://login.microsoftonline.com/ebbd6124-b361-.../v2.0/.well-known/openid-configuration
    callbackUrl: http://localhost:8082/callback
    clientId: <client-id>
    clientSecret: <client-secret>
    groupClaim: "groups"
```

And I hade no issue. Without knowledge about your environment I can't really help. Timeouts indicating issues with configuration or connections. From the application side I confirmed that its working with azure and I already know from other users that they using azure as oidc provider without this kind if issue.

**Comment by roshkovm** [comment]
Hello
Help me please with configuration for Google auth?
Thanks

**Comment by fjogeleit** [comment]
@sarg3nt do you use any kind of proxy for your auth service which is configured via env variables?

@roshkovm you can check the docs for oauth2 integration via google.

**Comment by roshkovm** [comment]
@fjogeleit I successfully configured oauth2, but i need to add restriction for specific group, which created in GCP: sso.kyverno.dev@domain.com.

How can i do it?
Thanks 


 ```
 oauth:
    enabled: true
    provider: google
    callbackUrl: https://kyverno-policy-reporter.${domain}/callback
    clientId: ${clientId}
    clientSecret: ${clientSecret}
```

**Comment by fjogeleit** [comment]
oauth does not support groups or permissions as oauth2 provides no group / permission model

**Comment by roshkovm** [comment]
@fjogeleit Can i replace oauth2 by openIDConnect?
```
  openIDConnect:
    enabled: true
    discoveryUrl: https://kyverno-policy-reporter.${domain}
    callbackUrl: https://kyverno-policy-reporter.${domain}/callback
    clientId: ${clientId}
    clientSecret: ${clientSecret}
    groupClaim: "groups"
    scopes:
    - openid
    - email
    - groups
 groupClaim: "<my gcp group id or group name>"
    skipTLS: false
```

**Comment by fjogeleit** [comment]
you can use google as openIDConnect provider and set the name of the group claim key in the user payload to limit access via groups.

**Comment by roshkovm** [comment]
@fjogeleit Do you mean? Correct?
`groupClaim: "group name>"`

**Comment by fjogeleit** [comment]
Yes, if your payload looks like e.g. `{ "username": "fjogeleit", "groups": ["user"]  }` then "groups" would be the groupClaim. Then you can use the mapped groups from google to restrict permissions.

**Comment by roshkovm** [comment]
@fjogeleit Sorry, i did not understand
In GCP i have created group: sso.kyverno.dev@domain.com.
Group ID: 0942exxxxx
Inside this group i have included users.
My settings should be:
groupClaim: sso.kyverno.dev@domain.com
?

**Comment by fjogeleit** [comment]
No, the group claim is the `key` within the JSON where this information is available. Your example is an actual value this property could have.

**Comment by roshkovm** [comment]
@fjogeleit Sorry, could you please provide me example of JSON. Which JSON file do you mean?
After creating web application and service account - i have some JSON, but no labels(key/value) inside.

**Comment by roshkovm** [comment]
@fjogeleit I see scopes option for oauth2:
Can i use like this?
Email: devops-team@domain.com contains list of email users.

```
clusters:
  - accessControl:
      emails:
      - devops-team@domain.com
    host: http://policy-reporter:8080
    name: Default
boards:
  accessControl:
    emails:
    - devops-team@domain.com

oauth:
   enabled: true
   provider: google
   callbackUrl: https://kyverno-policy-reporter.${domain}/callback
   clientId: ${clientId}
   clientSecret: ${clientSecret}
   scopes:
      - email
      - groups
```

OR

```
clusters:
  - accessControl:
      groups:
      - devops-team@domain.com
    host: http://policy-reporter:8080
    name: Default
boards:
  accessControl:
    groups:
    - devops-team@domain.com
   
  openIDConnect:
    enabled: true
    discoveryUrl: https://kyverno-policy-reporter.${domain}
    callbackUrl: https://kyverno-policy-reporter.${domain}/callback
    clientId: ${clientId}
    clientSecret: ${clientSecret}
    groupClaim: "groups"
    scopes:
    - openid
    - email
    - groups
 groupClaim: "<my gcp group id or group name>"
    skipTLS: false
```

Thanks
