### ISSUE TITLE
Authentication needs more details

### ISSUE THREAD

**Issue by hichem-belhocine** [fjogeleit/policy-reporter#761]
Hello,

I'd like to request the documentation in details how to setup authentication as It's not clear how to setup it in the official page.

As a good example, see https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/microsoft/#entra-id-app-registration-auth-using-oidc

If you could give an example how we could implement the authentication on **azure** using **openidConnect** and allow **specifc** Group to see only x customBoard would be **great** (Actually I implemented it but I cannot split the boards and implement the authorization)

Another issue that I got is when I add **accessControl** to **customBoards**, the **customBoard** does not appear in the **UI**?
Thanks

**Comment by fjogeleit** [comment]
which part do you struggle with? I am not very familiar with azure.

I tried a bit and it worked with this:

```yaml
ui:
  openIDConnect:
    enabled: true
    discoveryUrl: https://login.microsoftonline.com/<tenant-id>/v2.0/.well-known/openid-configuration
    callbackUrl: http://localhost:8082/callback
    clientId: 31adb89f-1162-404b-... # clientId
    clientSecret: <generated client secret> # certificate & secrets ->  new client secret key
    groupClaim: "groups"
```

Steps I did in azure:
* Create an App Policy Reporter
* Configure it as Web App with the callback API of your installation
* Generate a ClientSecret
* Under Token configuration -> Add `groups` as optional claim

When you configure access control with your Azure groups be aware that azure adds the roles with there IDs

```yaml
ui:
  customBoards:
    - name: Infrastructure
      namespaces:
        selector:
          team: infra
      accessControl:
        groups: [92ae7bb0-1720-4794-a47d-997bc000460c]

```

**Comment by fjogeleit** [comment]
I will try to improve the documentation over time but its a bit much to provide examples for all common OpenIDConnect clients.

**Comment by hichem-belhocine** [comment]
Thanks a lot for reply.


>When you configure access control with your Azure groups be aware that azure adds the roles with there IDs.

Thanks for clarifying, it works now.

The issue now is:

1) based in your example 

```
ui:
  customBoards:
    - name: Infrastructure
      namespaces:
        selector:
          team: infra
      accessControl:
        groups: [92ae7bb0-1720-4794-a47d-997bc000460c]
``` 

How can I allow Infrastructure team to see only their reports (authorization)


2) Another question is that I cannot filter based on Pod as shown in the screenshot

<img width="160" alt="Image" src="https://github.com/user-attachments/assets/6e03e637-6ba3-4a3b-8291-39d17b8a6f1c" />

3) It does not list all the policies as in V2

V2

<img width="864" alt="Image" src="https://github.com/user-attachments/assets/d7312fe7-ac8b-47e2-9324-262ff6c3768e" />

V3

<img width="805" alt="Image" src="https://github.com/user-attachments/assets/69521032-3a26-4b31-bd3b-d4a4b82aa563" />

**Comment by fjogeleit** [comment]
1. Currently CustomBoards only allow to filter a subset of namespaces, how would you like to define

> only their reports (authorization)

With a list of policy names?

2. Policy Reporter v3 has a new feature called `uncontrolledOnly`

https://kyverno.github.io/policy-reporter-docs/policy-reporter/report-processing.html#source-filter

It automatically skips all reports for Pod resurces if they are owned by a controller resource. This reduces duplication of information because kyverno generates in most cases duplicated reports for e.g. deployments, replicasets and pods.

If you do not have pods without a controller, it will not show any Pod report or filter.

3. Both lists are from the same cluster? It looks correct to me as the overall result number form the graph hits the sum of the displayed policies.

**Comment by hichem-belhocine** [comment]
As Admin, I would like to see everything, but for developers, I would like that each team can see only their namespaces
> Currently CustomBoards only allow to filter a subset of namespaces, how would you like to define

**Comment by fjogeleit** [comment]
filter namespaces is possible. As documented you can use a fixed list of namespaces or labels to select them.

In the example namspaces are selected via labels:

```yaml
      namespaces:
        selector:
          team: infra
```

**Comment by hichem-belhocine** [comment]
Yeah, but they will still see everything

<img width="128" alt="Image" src="https://github.com/user-attachments/assets/4e15565d-231c-4e78-abd2-9a4a8ba65c2e" />


Yes, Both lists are from the same cluster

>Both lists are from the same cluster?

**Comment by fjogeleit** [comment]
You can add accessControl to all default boards (currently not per board). This will hide these boards for your e.g. infra team:

```yaml
ui:
  boards:
    accessControl:
      groups: ['admin']
```

**Comment by hichem-belhocine** [comment]
It does not work, and concerning the groups you told me above 
>When you configure access control with your Azure groups be aware that azure adds the roles with there IDs

Did you test it? a screenshot can perhaps help

Thanks

**Comment by fjogeleit** [comment]
Sorry, I found an issue in the Helm Chart, which did not map the boards configuration into the UI config.

I tested it in my local setup, which worked.

Preparing a fix for it.

**Comment by hichem-belhocine** [comment]
Thanks a lot.

My hope is that developers could see only their custom borads and not the icons below

<img width="128" alt="Image" src="https://github.com/user-attachments/assets/c9cc9fb6-e6e3-4a7f-8d1f-9762322d6f64" />



And for your question 

>  Both lists are from the same cluster?

Yes,  Both lists are from the same cluster

**Comment by fjogeleit** [comment]
You can update to helm chart version `3.0.3`, this should fix the boards config mapping.

Could you provide a screen of the result of

```bash
kubectl get cpol -o wide
```

**Comment by fjogeleit** [comment]
> Yes, Both lists are from the same cluster

Do the missing policies provide any results?

Could be the case that policies which do not produce any result are not shown in this list. Will see if I can improve this when the kyverno plugin is used.

**Comment by hichem-belhocine** [comment]
Are you sure that 3.0.3 is published

```
helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "platform-tooling" chart repository
Update Complete. ⎈Happy Helming!⎈
```

```
helm search repo policy-reporter
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
platform-tooling/policy-reporter 3.0.0           3.0.0           Policy Reporter watches for PolicyReport Resour...
```

**Comment by fjogeleit** [comment]
Can you please check again? The publish action failed

**Comment by hichem-belhocine** [comment]
The same thing, there is only version 3.0.0

**Comment by fjogeleit** [comment]
This is the underlaying chart repo: https://kyverno.github.io/policy-reporter/index.yaml

As you see the latest item is Helm Chart Version 3.0.3 / App Version: 3.0.0

```bash
➜  policy-reporter git:(main) helm search repo policy-reporter

NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
policy-reporter/policy-reporter 3.0.3           3.0.0           Policy Reporter watches for PolicyReport Resour...
```

**Comment by hichem-belhocine** [comment]
It was an issue with cache, now I got chart version 3.0.3

Now looks better with customBoards, so now i can assign customBoards to developers based on groups. Thanks a lot

but Boards does not work as expected, Im not sure about the group name **admin**, where should I configure the admin group in the App or how? 

```
boards:
    accessControl:
      groups: ['admin']
``` 
I got

<img width="941" alt="Image" src="https://github.com/user-attachments/assets/1582692b-c0e8-4950-8a2c-41d2de42386d" />

**Comment by fjogeleit** [comment]
The `admin` group is only an example. It should be an azure group you have assigned to your admins. It follows the same logic as customBoard groups

**Comment by hichem-belhocine** [comment]
I added 
```
sourceFilters:
  - uncontrolledOnly: false
``` 
then I could see all my policies

another issue is when I try to use secretRef to authenticate, the secret get not mounted into the deployment and I already opened a PR for it https://github.com/kyverno/policy-reporter/pull/771

**Comment by fjogeleit** [comment]
I just released a new Helm Chart version which should display your policies in the list even if they don't produce a result.

This is not how secretRefs working. They don't need to be attached to the deployment. They are fetched at runtime.

See https://github.com/kyverno/policy-reporter-ui/blob/main/backend/pkg/kubernetes/secrets/client.go#L35 for the expected keys of the secret

**Comment by fjogeleit** [comment]
https://kyverno.github.io/policy-reporter-docs/policy-reporter-ui/authentication.html has examples under "helm + secretRefs".

**Comment by hichem-belhocine** [comment]
I tested it with secretRef a lot of times but it does not work and also when decode the **policy-reporter-ui-config** secret, I got

```
namespace: kyverno

tempDir: /tmp

logging:
  api: false
  server: false
  encoding: console
  logLevel: 0

server:
  port: 8080
  cors: true
  overwriteHost: true

ui:
  displayMode:
  banner:
  logo:
    path:
    disabled: false

clusters:
  - name: Default
    secretRef: policy-reporter-ui-default-cluster

sources:
  - name: kyverno
    type: result
    exceptions: false
    excludes:
      results:
      - warn
      - error
openIDConnect:
    callbackUrl: https://kyverno-policy-reporter-ui/callback
    clientId: ""
    clientSecret: ""
    discoveryUrl: ""
    enabled: true
    groupClaim: groups
    scopes:
    - openid
    secretRef: policy-reporter-ui-sso
oauth:
    callbackUrl: ""
    clientId: ""
    clientSecret: ""
    enabled: false
    provider: ""
    scopes: []
    secretRef: ""
``` 

and when I add the secret to values.yaml file, I got

```
namespace: kyverno

tempDir: /tmp

logging:
  api: false
  server: false
  encoding: console
  logLevel: 0

server:
  port: 8080
  cors: true
  overwriteHost: true

ui:
  displayMode:
  banner:
  logo:
    path:
    disabled: false

clusters:
  - name: Default
    secretRef: policy-reporter-ui-default-cluster

sources:
  - name: kyverno
    type: result
    exceptions: false
    excludes:
      results:
      - warn
      - error
openIDConnect:
    callbackUrl: https://kyverno-policy-reporter-ui/callback
    clientId: "*******************"
    clientSecret: "*********************"
    discoveryUrl: "https://login.microsoftonline.com/****************/v2.0/.well-known/openid-configuration"
    enabled: true
    groupClaim: groups
    scopes:
    - openid
    secretRef: ""
oauth:
    callbackUrl: ""
    clientId: ""
    clientSecret: ""
    enabled: false
    provider: ""
    scopes: []
    secretRef: ""
```

**Comment by hichem-belhocine** [comment]
could you reopen it please

**Comment by fjogeleit** [comment]
will check again but as I already mentioned. Its fetched at runtime, you will not see the values in the other secret / config

**Comment by hichem-belhocine** [comment]
Thanks a lot for replying.

The authentication works when we set the **discoveryUrl** in the values and not in the secret with **clientId** and **clientSecret**.

we have another issue now, we are using the nginx ingress controller (not the community one) on the clusters, and when we set **ui.replicaCoun**t to **3**, something goes wrong because the auth requires the sessions if there are multiple replicas, any idea how we can solve it (the ingress)?

**Comment by hichem-belhocine** [comment]
another issue now we can not see the pod reports with the new version even with 

```
sourceFilters:
  - uncontrolledOnly: false
``` 

Thanks

**Comment by fjogeleit** [comment]
> another issue now we can not see the pod reports with the new version even with
> 
> ```
> sourceFilters:
>   - uncontrolledOnly: false
> ```
> 
> Thanks

doesn not work anyway. You need to set the selector for kyverno

```yaml
sourceFilters:
- selector:
    source: kyverno
  uncontrolledOnly: false
  disableClusterReports: false
  kinds:
    exclude: [ReplicaSet]
```

**Comment by hichem-belhocine** [comment]
it does not show the pods even after restarting pods

<img width="260" alt="Image" src="https://github.com/user-attachments/assets/b115b56c-07da-4fe1-9955-27a53f36029a" />

**Comment by achaikaJH** [comment]
> which part do you struggle with? I am not very familiar with azure.
> 
> I tried a bit and it worked with this:
> 
> ui:
>   openIDConnect:
>     enabled: true
>     discoveryUrl: https://login.microsoftonline.com/<tenant-id>/v2.0/.well-known/openid-configuration
>     callbackUrl: http://localhost:8082/callback
>     clientId: 31adb89f-1162-404b-... # clientId
>     clientSecret: <generated client secret> # certificate & secrets ->  new client secret key
>     groupClaim: "groups"
> Steps I did in azure:
> 
> * Create an App Policy Reporter
> * Configure it as Web App with the callback API of your installation
> * Generate a ClientSecret
> * Under Token configuration -> Add `groups` as optional claim
> 
> When you configure access control with your Azure groups be aware that azure adds the roles with there IDs
> 
> ui:
>   customBoards:
>     - name: Infrastructure
>       namespaces:
>         selector:
>           team: infra
>       accessControl:
>         groups: [92ae7bb0-1720-4794-a47d-997bc000460c]

Hi @fjogeleit 
I'm trying to set this up with azure. My config is below. Authentication part is working fine but authorisation doesn't, allowing users which aren't part of specified group to see any board.
I'm using helm chart version 3.0.4. Not sure what am I missing.

```yaml
ui:
  enabled: true
    openIDConnect:
      # -- Enable openID Connect authentication
      enabled: true
      # -- OpenID Connect Discovery URL
      discoveryUrl: "https://login.microsoftonline.com/tenantId/v2.0"
      # -- OpenID Connect Callback URL
      callbackUrl: "https://reporter-host/callback"
      # -- OpenID Connect ClientID
      clientId: ""
      # -- OpenID Connect ClientSecret
      clientSecret: ""
      # -- Optional Group Claim to map user groups to the profile
      # groups can be used to define access control for clusters, boards and custom boards.
      groupClaim: "groups"
      # -- OpenID Connect allowed Scopes
      scopes: ["openid"]
      boards:
        accessControl:
          groups: ["xxxxxxxx-xxxx-xxxx-xxxx-08bffc32272a"]
```

**Comment by fjogeleit** [comment]
I think boards should be under ui and Not openIDConnect. So your indentation Looks wrong

**Comment by achaikaJH** [comment]
> I think boards should be under ui and Not openIDConnect. So your indentation Looks wrong

you are 100% right!
What a silly mistake! 
Everything is working now. 
Thank you for your help!

**Comment by fjogeleit** [comment]
@hichem-belhocine sorry for the late response, do you still encounter issues?

**Comment by hichem-belhocine** [comment]
Actually yes, we have an issue with **openIDConnect** when we upgrade from **3.0.7** to **3.1.3**

```shell
1.74532596187031e+09 info config/resolver.go:172 values loaded from secret {"secretRef": "policy-reporter-ui-sso"}
1.7453259626985931e+09 info auth/router.go:74 setup oauth routes
1.745325962776468e+09 info config/resolver.go:172 values loaded from secret {"secretRef": "policy-reporter-ui-default-cluster"}
1.7453259627767777e+09 info config/resolver.go:399 register UI {"path": "/var/run/ko/ui"}
1.7453259627771363e+09 info cmd/run.go:35 Server starts {"port": 8080}
2025/04/22 12:46:34 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:34 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:34 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:36 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:36 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:36 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:36 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:36 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
2025/04/22 12:46:38 ERROR [sessions] ERROR! err="open /tmp/session_FYBI6B6P2RCPW2SDFVDSFVDFVOXBFZ366ZA6JCPKXYALJ6XQ35Q: no such file or directory"
1.7453259983702126e+09 error auth/middleware.go:47 profile not found
1.7453260001885965e+09 error auth/handler.go:24 failed to complete user {"error": "Get \"https://graph.microsoft.com/oidc/userinfo\": read tcp x.x.x.x:55226->x.x.x.x:443: read: connection reset by peer"}
```

**Comment by fjogeleit** [comment]
@hichem-belhocine sorry for Late response. The UI had an issue leading to this error After restarts. The latest Version should fix this

**Comment by fjogeleit** [comment]
Does this lead to issues in the UI? This error Happens after a restart. When the browser session is no longer available in the pod filesystem. The latest Version should replace the Session Cookie with a new One in this case.

**Comment by hichem-belhocine** [comment]
>Does this lead to issues in the UI?

yes


after restarting the pod, I got those logs:
```
1.7458284268623338e+09 info config/resolver.go:172 values loaded from secret {"secretRef": "policy-reporter-ui-sso"}
1.745828427428981e+09 info auth/router.go:74 setup oauth routes
1.7458284275389633e+09 info config/resolver.go:172 values loaded from secret {"secretRef": "policy-reporter-ui-default-cluster"}
1.7458284275390415e+09 info config/resolver.go:399 register UI {"path": "/var/run/ko/ui"}
1.7458284275391247e+09 info cmd/run.go:35 Server starts {"port": 8080}
1.745828458288366e+09 error auth/middleware.go:47 profile not found
1.74582845832458e+09 error auth/middleware.go:47 profile not found
1.7458284594764357e+09 error auth/handler.go:24 failed to complete user {"error": "Get \"https://graph.microsoft.com/oidc/userinfo\": read tcp x.x.x.x:48808->x.x.x.x:443: read: connection reset by peer"}
1.7458286048063235e+09 error auth/handler.go:24 failed to complete user {"error": "could not find a matching session for this request"}
1.745828607482702e+09 error auth/middleware.go:47 profile not found
1.745828607508549e+09 error auth/middleware.go:47 profile not found
1.7458286089636147e+09 error auth/handler.go:24 failed to complete user {"error": "Get \"https://graph.microsoft.com/oidc/userinfo\": read tcp x.x.x.x:37722->x.x.x.x:443: read: connection reset by peer"}
1.7458299482632492e+09 error auth/middleware.go:47 profile not found
1.7458299482962816e+09 error auth/middleware.go:47 profile not found
1.745829949755303e+09 error auth/handler.go:24 failed to complete user {"error": "Get \"https://graph.microsoft.com/oidc/userinfo\": read tcp x.x.x.x:37582->x.x.x.x:443: read: connection reset by peer"}
``` 

<img width="937" alt="Image" src="https://github.com/user-attachments/assets/82bf4441-b90b-4b01-a62b-93e9a13e6e09" />


But when I revert the version, it works as expected/

**Comment by fjogeleit** [comment]
Okay, let me check something

**Comment by fjogeleit** [comment]
Can you pls check if `ui.image.tag` = `2.3.7-rc.1` works?

**Comment by hichem-belhocine** [comment]
the same issue

**Comment by fjogeleit** [comment]
Can you try `ui.image.tag` = `2.3.7-rc.2`

I added some HTTP Client config defaults between  UI 2.2.0 and 2.3.6, I assume they are the reason. I reduced them to see if its the course of your issue.

**Comment by hichem-belhocine** [comment]
unfortunately always the same issue

chart version == 3.1.3
ui.image.tag == 2.3.7-rc.2

**Comment by fjogeleit** [comment]
I created `2.3.7-rc.3` with just the default http.Client as before. To ensure that it really relates to the client defaults

**Comment by hichem-belhocine** [comment]
Now, it works

**Comment by fjogeleit** [comment]
okay, really strange, thanks for checking. Would be interesting which configuration leads to your issue.

**Comment by hichem-belhocine** [comment]
I'm using this configuration as I mentioned before
```
openIDConnect:
    enabled: true
    discoveryUrl: "https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxx/v2.0/.well-known/openid-configuration"
    callbackUrl: "https://kyverno-policy-reporter-ui.xxxxxxxxxxxxx/callback"
    scopes:
      - openid
    groupClaim: "groups"
    secretRef: "policy-reporter-ui-sso"
```

**Comment by fjogeleit** [comment]
Do you use any kind of proxy in between? I think the reason could be that I did not set `Proxy: http.ProxyFromEnvironment`. So it did not pick up proxy environment variables

**Comment by hichem-belhocine** [comment]
Yes, I added the proxy under:
```
ui:
   envVars:
       - name:
       - value
```

**Comment by fjogeleit** [comment]
Could you please try `2.3.7-rc.4`? I added the proxy logic to my defaults. So it should now still work.

**Comment by hichem-belhocine** [comment]
<img width="945" alt="Image" src="https://github.com/user-attachments/assets/bb9ead5f-b496-4a06-ab55-384163098a00" />

all other icons are disappeared 
<img width="128" alt="Image" src="https://github.com/user-attachments/assets/c9cc9fb6-e6e3-4a7f-8d1f-9762322d6f64" />

**Comment by fjogeleit** [comment]
So for both - `2.3.7-rc.3` and `2.3.7-rc.4`?

**Comment by fjogeleit** [comment]
You can set:

```yaml
ui:
  logging:
    logLevel: -1
```

To see the assigned user roles in the logs. You should also see in the logs when the role mapping did not work for any reason.

**Comment by hichem-belhocine** [comment]
>So for both - 2.3.7-rc.3 and 2.3.7-rc.4?

2.3.7-rc.4

**Comment by fjogeleit** [comment]
With `2.3.7-rc.3` you don't have any issue?

**Comment by hichem-belhocine** [comment]
>With 2.3.7-rc.3 you don't have any issue?

yes

**Comment by fjogeleit** [comment]
Okay, strange. Thanks for your support. Then I stick with the default client configurations for now.

**Comment by hichem-belhocine** [comment]
Thanks a lot for you help

**Comment by fjogeleit** [comment]
I tagged `2.3.7` should be available in the next 10 minutes. Will try to create a new helm release during the week.

**Comment by roshkovm** [comment]
Hello
Help me please with configuration for Google auth.
Thanks.

**Comment by fjogeleit** [comment]
You can check the required configurations in the docs https://kyverno.github.io/policy-reporter-docs/policy-reporter-ui/authentication.html#oauth2

**Comment by roshkovm** [comment]
@fjogeleit I tested few configurations. All are fail(
**Configuration 1:**

```
  ui:
    openIDConnect:
      enabled: true
      discoveryUrl: https://accounts.google.com/o/oauth2/auth
      callbackUrl: "https://policy-reporter.domain/api/dex/callback"
      clientId: "xxxxxxxxx"
      clientSecret: "yyyyyyy"
      scopes:
      - openid
      skipTLS: true

      groupClaim: "groups"
```

**Got issue:**
"msg":"failed to create openIDConnect provider","error":"Non-success code for Discovery URL: 404"}


**Configuration 2:**

```
ui:
  oauth:
    enabled: true
    provider: google
    callbackUrl: "https://policy-reporter.domain/api/dex/callback"
    clientId: "xxxxxxxxx"
    clientSecret: "yyyyyyy"
    scopes: []
```

**Got issue:**
WEB browser:
https://policy-reporter.domain/api/dex/login
If the problem continues, contact the site owner.
HTTP ERROR 401

**Configuration 3:**

```
ui:
  oauth:
    enabled: true
    provider: google
    callbackUrl: "https://policy-reporter.domain/callback"
    clientId: "xxxxxxxxx"
    clientSecret: "yyyyyyy"
    scopes: []
```

**Got issue:**
WEB browser:
Access blocked: This app’s request is invalid
Error 400: redirect_uri_mismatch

**Comment by fjogeleit** [comment]
Ensure you have configured the correct redirect uri in the google console:

<img width="523" alt="Image" src="https://github.com/user-attachments/assets/cee0cf98-84be-4805-ba9f-ca6ff02ca97c" />

```yaml
oauth:
  enabled: true
  provider: google
  clientId: xxxx.apps.googleusercontent.com
  clientSecret: ***********
  callbackUrl: http://localhost:8082/callback
```
