### ISSUE TITLE
Wrong image repository

### ISSUE THREAD

**Issue by srekkas** [fjogeleit/policy-reporter#769]
I think image repository is wrong, stock helm do not download image for me.
But if i fix to "kyverno/charts/policy-reporter" , container wont start.

**Comment by fjogeleit** [comment]
Which Image do you exactly mean? Chart repo is for Opi Helm Chart Installation

**Comment by srekkas** [comment]
I tried install as per documentation without any changes and got image not found.

```
fullnameOverride: "policy-reporter"

# -- Overwrite the namespace of all resources
namespaceOverride: ""

image:
  # -- (string) Image registry
  registry: ghcr.io
  # -- (string) Image repository
  repository: kyverno/policy-reporter
```
