### ISSUE TITLE
Policy Reporter (and UI) not showing all policy failures

### ISSUE THREAD

**Issue by aRobinson-R7** [fjogeleit/policy-reporter#836]
Kyverno version: 3.3.7
Policy-Reporter version: 3.0.3
Policy-Reporter UI version: 2.2.0

Policy Reporter is not reporting all of the `policyreport` failures generated by Kyverno, it seems to only report for certain resources / policies.
We are using the metrics endpoint to push results to Datadog for tracking but this is also visible in the policy-reporter-ui as well as when directly querying the `/metrics` endpoint.

These policies are all visible when querying for `policyreports`. Are the numbers just too high, is there a setting we are missing?
Looking at policyreports we can see some policy failures getting reported but not others, for the same resource.

For example, we have a policy to audit when the default serviceaccount is used by a pod:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-serviceaccount-usage
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Track Default Serviceaccount Usage
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Tracking the usage of the default Serviceaccount across all workloads. Will ensure any changes
      made to the serviceaccount are validated first.
spec:
  validationFailureAction: "Audit"
  background: true
  rules:
  - name: validate-serviceaccount
    match:
      any:
      - resources:
          kinds:
          - Pod
    {{- include "exclusionRule" . | indent 4 }}
    validate:
      message: "Pod using 'default' serviceaccount"
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.serviceAccountName || '' }}"
            operator: Equals
            value: default
            message: The expression serviceAccountName = default failed.
          - key: "{{ request.object.spec.serviceAccountName || '' }}"
            operator: Equals
            value: ''
            message: The expression serviceAccountName = null failed.
```

If we "describe" a policyreport for a pod meeting the criteria we can see it has failed (this is true for many pods):

![Image](https://github.com/user-attachments/assets/2d295fb0-5ebb-423a-aed0-aef606594797)

However it never appears to get picked up by policy-reporter:

![Image](https://github.com/user-attachments/assets/02198135-de92-41aa-ba37-366b9dfe5ab4)

**Comment by fjogeleit** [comment]
Hey, I think your issue relates to the default sourceFilter for kyvernowhich sets `uncontrolledOnly` to true. This filter automatically all reports which relates to a pod resource which is controlled by a replicaset/deployment/daemonset etc.

Because you are setting `pod-policies.kyverno.io/autogen-controllers: none` you do not have policy reports for the controller resources.

You can override the default so set it to false.

```yaml
sourceFilters:
  - selector:
      source: kyverno
    uncontrolledOnly: false
    disableClusterReports: false
    kinds:
      exclude: [ReplicaSet]
```
