### ISSUE TITLE
`panic: Lock identity is empty` thrown when the Kyverno Plugin is replicaCount > 1 and blockReports is set to true.

### ISSUE THREAD

**Issue by larssb** [fjogeleit/policy-reporter#846]
Here's to my fellow `Kyverno Policy Reporter` users.

On v3.0.3 - when configuring:

```yaml
....
....
....
....
#
# Kyverno Policy Reporter Kyverno Plugin configuration
#
plugin:
  kyverno:
    enabled: true
    replicaCount: 1
    logging:
      server: true
      encoding: json
      logLevel: 4
    blockReports:
      enabled: true
      eventNamespace: ""
  resources:
    limits:
      #!cpu: null
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 150Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
          topologyKey: "kubernetes.io/hostname"
....
....
....
....
```

I see the following error in the `policy-reporter-kyverno-plugin-* Pods`: `panic: Lock identity is empty`.

**Here's the full thrown error:**

```text
{"level":"info","ts":1742981355.9245334,"caller":"cmd/run.go:56","msg":"block reports enabled","resultsPerRepor
{"level":"info","ts":1742981355.9251993,"caller":"cmd/run.go:132","msg":"server starts","port":8080}
panic: Lock identity is empty

goroutine 8 [running]:
k8s.io/client-go/tools/leaderelection.RunOrDie({0x24d1e18, 0x370afa0}, {{0x24d67d0, 0xc0003cca20}, 0x37e11d600,
    k8s.io/client-go@v0.32.1/tools/leaderelection/leaderelection.go:230 +0xab
github.com/kyverno/policy-reporter/kyverno-plugin/pkg/kubernetes/leaderelection.(*Client).Run(0xc00045f080, {0x
    github.com/kyverno/policy-reporter/kyverno-plugin/pkg/kubernetes/leaderelection/client.go:47 +0x228
github.com/kyverno/policy-reporter/kyverno-plugin/cmd.newRunCMD.func1.5()
    github.com/kyverno/policy-reporter/kyverno-plugin/cmd/run.go:109 +0x29
golang.org/x/sync/errgroup.(*Group).Go.func1()
    golang.org/x/sync@v0.10.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
    golang.org/x/sync@v0.10.0/errgroup/errgroup.go:75 +0x96
```

---

Looking through how the `poicy-reporter-kyverno-plugin Pods` are templated and can't figure out why.

---

1. This file: https://github.com/kyverno/policy-reporter/blob/v3.0.3/charts/policy-reporter/configs/kyverno-plugin.tmpl is used by 
2. this file: https://github.com/kyverno/policy-reporter/blob/main/charts/policy-reporter/templates/plugins/kyverno/config-secret.yaml

So when I set `replicaCount: 2` and `blockReports.enabled: true` that should ensure that `leader election` is properly configured. Controlling the `policy-reporter-kyverno-plugin-config Secret` configured in this case I see:

```text
kubectl get secret policy-reporter-kyverno-plugin-config -n kyverno-policy-reporter -o yaml | yq '.data."config.yaml"' | base64 -d

>>>><<<<

leaderElection:
  enabled: true
  releaseOnCancel: true
  leaseDuration: 15
  renewDeadline: 10
  retryPeriod: 2
  lockName: kyverno-plugin

logging:
  api: false
  server: true
  encoding: json
  logLevel: 0

server:
  basicAuth:
    username: 
    password: 
    secretRef: 

core:
  host: http://policy-reporter:8080
blockReports:
    enabled: true
    policyReport:
      annotations: []
      labels: []
    results:
      keepOnlyLatest: false
      maxPerReport: 200
    source: Kyverno Event
```

So there's a lock name and so on. 

Conclusion, on my part: Why the dang is this failing? Can't figure out why.

---

If I configure `blockReports.enabled: true` and `replicaCount: 1` then the `Kyverno Plugin Pods` comes up `healthy` and `running`.

---

- Am I doing something wrong in the way I configure the workload?
- Or is this a bug?

Looking forward to hearing from anyone in the know. Thank you so much.
