### ISSUE TITLE
Getting multi-tenancy with basic auth. on downstream cluster Kyverno Reporter API's to work.

### ISSUE THREAD

**Issue by larssb** [fjogeleit/policy-reporter#847]
# I'm trying to configure the following setup

1. One UI on a management Kubernetes cluster
1. Downstream clusters
    1. No UI. Only reporter and Kyverno plugin 
    2. Exposing the API via `rest.enabled: true` and `Ingress` on both the `Kyverno Pol. Reporter` and `Kyverno plugin` workloads
    3. Basic auth. is set to `secretRef` and the global level in the values file. And a Secret containing username and password is created in the namespace of the reporter
 1. Management UI gets basic auth. data and other data needed ( as described on: https://kyverno.github.io/policy-reporter-docs/policy-reporter-ui/multi-tenant.html )

## Result

I can select between different Kyverno Policy Reporter's in the UI. However, nothing is displayed in the UI and the `policy-reporter ui` report:

```text
{"level":"info","ts":1743005303.8112752,"caller":"zap@v1.1.4/zap.go:117","msg":"/proxy/CLUSTER-NAME-kyverno-policy-reporter-ui/core/v1/cluster-resources/kinds","status":404,"method":"GET","path":"/proxy/CLUSTER-NAME-kyverno-policy-reporter-ui/core/v1/cluster-resources/kinds","query":"","ip":"10.1.125.116","user-agent":"Mozilla/5.0 (X11; OS-NAME; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","latency":0.000061371,"time":"2025-03-26T16:08:23Z"}
{"level":"info","ts":1743005303.8118513,"caller":"zap@v1.1.4/zap.go:117","msg":"/api/config/CLUSTER-NAME-kyverno-policy-reporter-ui/namespaces","status":500,"method":"GET","path":"/api/config/CLUSTER-NAME-kyverno-policy-reporter-ui/namespaces","query":"","ip":"10.1.125.116","user-agent":"Mozilla/5.0 (X11; OS-NAME; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","latency":0.000818283,"time":"2025-03-26T16:08:23Z"}
{"level":"info","ts":1743005303.8309112,"caller":"zap@v1.1.4/zap.go:117","msg":"/api/config/CLUSTER-NAME-kyverno-policy-reporter-ui/dashboard","status":404,"method":"GET","path":"/api/config/CLUSTER-NAME-kyverno-policy-reporter-ui/dashboard","query":"","ip":"10.1.125.116","user-agent":"Mozilla/5.0 (X11; OS-NAME; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","latency":0.000953684,"time":"2025-03-26T16:08:23Z"}
{"level":"error","ts":1743005303.8640635,"caller":"api/handler.go:95","msg":"failed to list namespaces","cluster":"CLUSTER-NAME-kyverno-policy-reporter-ui","error":"client for cluster not found"}
{"level":"info","ts":1743005303.8641732,"caller":"zap@v1.1.4/zap.go:117","msg":"/api/config/CLUSTER-NAME-kyverno-policy-reporter-ui/namespaces","status":500,"method":"GET","path":"/api/config/CLUSTER-NAME-kyverno-policy-reporter-ui/namespaces","query":"","ip":"10.1.125.116","user-agent":"Mozilla/5.0 (X11; OS-NAME; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0","latency":0.000264218,"time":"2025-03-26T16:08:23Z"}
```

CLUSTER-NAME-kyverno-policy-reporter-ui, real name of course something else, do exist in the `namespace` of the `Kyverno Policy Reporter`. Hence the capability to actually have the drop-down selector in the UI. To switch between different downstream clusters Kyverno Pol. installation.

---

### Main cluster ( management cluster ) - where the Kyverno Policy UI is running

1. Having the Kyverno Policy Reporter installed on a "management" cluster
    1. This installation is having the following values:
 
```yaml
#
# Core Kyverno Policy Reporter configuration
#
replicaCount: 2

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 25m
    memory: 100Mi

logging:
  server: true
  encoding: json

metrics:
  enabled: true
  mode: simple

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
        topologyKey: "kubernetes.io/hostname"

#
# Kyverno Policy Reporter UI configuration
#
ui:
  enabled: true
  name: SOME_NAME
  replicaCount: 2
  logging:
    server: true
    encoding: json
  displayMode: dark
  clusters:
  # Here ytt templating is used https://carvel.dev/ytt/
  #@ for cluster in data.values.clusters:
  - name: #@ cluster + "-kyverno-policy-reporter-ui"
    #! The secret is generated in the preAction.sh script
    secretRef: #@ cluster + "-kyverno-policy-reporter-ui"
  #@ end
  ingress:
    enabled: true
    className: haproxy
    annotations:
      cert-manager.io/issuer: step-cluster-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer-group: certmanager.step.sm
      cert-manager.io/revision-history-limit: "5"    
    hosts:
    - host: kpr.(@= data.values.cluster.replace("-", ".") @).a.domain
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: kpr-ui-tls-certs
      hosts:
      - kpr.(@= data.values.cluster.replace("-", ".") @).a.domain
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 150Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
          topologyKey: "kubernetes.io/hostname"

#
# Kyverno Policy Reporter Kyverno Plugin configuration
#
plugin:
  kyverno:
    enabled: true
    image:
      tag: 0.4.2
    replicaCount: 2
    logging:
      server: true
      encoding: json
      logLevel: 4
    blockReports:
      enabled: true
      eventNamespace: null
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 150Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                  - "true"
            topologyKey: "kubernetes.io/hostname"
```

**Example downstream secretRef**

```yaml
certificate: |
  -----BEGIN CERTIFICATE-----
  .....
  .....
  -----END CERTIFICATE-----
host: https://kpr.a.domain
password: MY-PASSWORD
plugin.kyverno: '{"host":"https://kpr-plugin.a.domain/api","name":"kyverno"}'
username: MY-USER
```

---

### Downstream clusters - where the UI on the management cluster calls the API's

The config:

```yaml
#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
#!
#! Core Kyverno Policy Reporter configuration
#!
replicaCount: 2

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 25m
    memory: 100Mi

rest:
  enabled: true
ingress:
  enabled: true
  className: haproxy
  annotations:
    cert-manager.io/issuer: step-cluster-issuer
    cert-manager.io/issuer-kind: StepClusterIssuer
    cert-manager.io/issuer-group: certmanager.step.sm
    cert-manager.io/revision-history-limit: "5"
  hosts:
  - host: kpr.(@= data.values.cluster.replace("-", ".") @).k8s.nemlig
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: kpr-api-tls-certs
    hosts:
    - kpr.(@= data.values.cluster.replace("-", ".") @).k8s.nemlig
basicAuth:
  secretRef: #@ data.values.cluster + "-kyverno-policy-reporter-ui"

logging:
  server: true
  encoding: json

metrics:
  enabled: true
  mode: simple

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - "true"
        topologyKey: "kubernetes.io/hostname"

#
# Kyverno Policy Reporter Kyverno Plugin configuration
#
plugin:
  kyverno:
    enabled: true
    image:
      tag: 0.4.2
    replicaCount: 2
    logging:
      server: true
      encoding: json
      logLevel: 4
    blockReports:
      enabled: true
      eventNamespace: null
    ingress:
      enabled: true
      className: haproxy
      annotations:
        cert-manager.io/issuer: step-cluster-issuer
        cert-manager.io/issuer-kind: StepClusterIssuer
        cert-manager.io/issuer-group: certmanager.step.sm
        cert-manager.io/revision-history-limit: "5"
      hosts:
      - host: kpr-plugin.(@= data.values.cluster.replace("-", ".") @).a.domain
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - secretName: kpr-plugin-tls-certs
        hosts:
        - kpr-plugin.(@= data.values.cluster.replace("-", ".") @).a.domain
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 150Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                  - "true"
            topologyKey: "kubernetes.io/hostname"

```

---

### On a downstream cluster

1. port-forward to the kyverno policy reporter
2. call:

```text
curl -v http://localhost:8080/healthz
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /healthz HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Wed, 26 Mar 2025 16:34:14 GMT
< Content-Length: 2
< 
* Connection #0 to host localhost left intact
*
```

So it's up and running ... however I can't figure out what actual API endpoint to call.

/api just gives HTTP404.

I was also thinking that I would be prompted or get HTTP403 when curl'ing the /api endpoint when basic auth. is enabled.

### Issues I've looked at

https://github.com/kyverno/policy-reporter/issues/548
https://github.com/kyverno/policy-reporter/issues/761
https://github.com/kyverno/policy-reporter/issues/336

---

I must be doing something wrong somewhere.

Looking forward to an advice or two 👍 - thank you so much.
