### ISSUE TITLE
Support skipExisting for targets created with TargetConfigs

### ISSUE THREAD

**Issue by aerosouund** [fjogeleit/policy-reporter#857]
currently, targets created via the CRD skip all existing resources by default. We would ideally have them support skipExisting to be true or false
cc: @fjogeleit

**Comment by fjogeleit** [comment]
Issue to solve:

* Load and send all results which already existed before the CRD was created
* How we want to handle updates, e.g. how to process changed filters?

**Comment by agardnerIT** [comment]
[This docs example ](https://kyverno.github.io/policy-reporter-docs/policy-reporter/integrations.html#webhook) is wrong.

```
apiVersion: policyreporter.kyverno.io/v1alpha1
kind: TargetConfig
metadata:
  name: dynatrace-example
spec:
  skipExistingOnStartup: true
  webhook:
    webhook: 'https://example.com'
    ....
```

Leads to:

```
Error from server (BadRequest): error when creating "target-config.yaml": TargetConfig in version "v1alpha1" cannot be handled as a TargetConfig: strict decoding error: unknown field "spec.skipExistingOnStartup"
```
