### ISSUE TITLE
Unable to push to security hub when upgraded from 2.23.0 to 3.1.1

### ISSUE THREAD

**Issue by geevanakash** [fjogeleit/policy-reporter#909]
Hello Team,

We recently upgraded Kyverno Policy Reporter from version 2.23.0 to 3.1.1 using Helm, following the official [upgrade guide](https://kyverno.github.io/policy-reporter-docs/upgrade-guide/helm.html).
The pods are running as expected; however, the policy-reporter pod is consistently encountering a 403 AccessDeniedException error when attempting to push findings to AWS SecurityHub.

**Summary of the Issue:**

The pod attempts to push findings to SecurityHub but receives a 403 error.

We are mounting AWS credentials into the pod from AWS Secrets Manager.

These credentials have been manually verified: using the same credentials outside the pod, we can successfully run aws securityhub batch-import-findings --findings, confirming that the credentials and permissions themselves are correct.

Error logs:
```
1.7458527719926636e+09  error   SecurityHub: PUSH FAILED        {"error": "operation error SecurityHub: BatchImportFindings, https response error StatusCode: 403, RequestID: xxxxxxxxxxxxxxxxx, api error AccessDeniedException: User: arn:aws:iam::111111111111111:user/test-pdev-share1-policy-reporter-service-account is not authorized to perform: securityhub:BatchImportFindings", "response": null}
1.7458527723146515e+09  error   SecurityHub: PUSH FAILED        {"error": "operation error SecurityHub: BatchImportFindings, https response error StatusCode: 403, RequestID: xxxxxxxxxxxxxxxxx, api error AccessDeniedException: User: arn:aws:iam::111111111111111:user/test-pdev-share1-policy-reporter-service-account is not authorized to perform: securityhub:BatchImportFindings", "response": null}
```

Below is the supplied values.yaml

```
tolerations:
- key: hyperion/karpenter-node-pool
  operator: "Equal"
  value: "test-default-node-pool"
  effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/nodepool
          operator: In
          values:
          - test-default-node-pool
global:
  labels: {}
image:
  pullPolicy: IfNotPresent
  registry: 1111111111111.dkr.ecr.eu-central-1.amazonaws.com
  repository: kyverno/policy-reporter
  tag: 3.1.1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: test-issuer
    cert-manager.io/duration: 2160h
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  className: private-ingress
  enabled: true
  hosts:
  - host: api.policy-reporter-share1.pdev.net
    paths:
    - backend:
        service:
          name: policy-reporter
          port:
            number: 8080
      path: /
      pathType: Prefix
  tls:
  - hosts:
    - api.policy-reporter-share1.pdev.net
    secretName: tls-policy-reporter-secret
plugin:
  kyverno:
    enabled: true
    server:
      port: 8080
    tolerations:
    - key: hyperion/karpenter-node-pool
      operator: "Equal"
      value: "test-default-node-pool"
      effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: karpenter.sh/nodepool
              operator: In
              values:
              - test-default-node-pool
    image:
      pullPolicy: IfNotPresent
      registry: 1111111111111.dkr.ecr.eu-central-1.amazonaws.com
      repository: kyverno/policy-reporter/kyverno-plugin
      tag: 0.4.2
    podAnnotations:
      hyperion/allow-sa-automount: "true"
    resources:
      limits:
        cpu: 30m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
livenessProbe:
  httpGet:
    path: /ready
    port: http
podAnnotations: {}
podLabels: {}
policyPriorities:
  default: warning
readinessProbe:
  initialDelaySeconds: 60
  httpGet:
    path: /healthz
    port: http
resources:
  limits:
    cpu: 60m
    memory: 64Mi
  requests:
    cpu: 30m
    memory: 32Mi
rest:
  enabled: true
target:
  securityHub:
    accountId: 1111111111111
    customFields:
      environment: pdev
      kube_cluster_name: test-euc1-pdev-share1-eks-cluster
    endpoint: https://securityhub.eu-central-1.amazonaws.com
    minimumSeverity: warning
    region: eu-central-1
    skipExistingOnStartup: true
    synchronize: true
    delayInSeconds: 2
    mountedSecret: "/mnt/secrets-store/policy-reporter-sm"
    sources:
    - kyverno
ui:
  tolerations:
  - key: hyperion/karpenter-node-pool
    operator: "Equal"
    value: "test-default-node-pool"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: karpenter.sh/nodepool
            operator: In
            values:
            - test-default-node-pool
  enabled: true
  image:
    pullPolicy: IfNotPresent
    registry: 1111111111111.dkr.ecr.eu-central-1.amazonaws.com
    repository: kyverno/policy-reporter-ui
    tag: 2.3.5
  resources:
    limits:
      cpu: 30m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    eks.amazonaws.com/role-arn: arn:aws:iam::1111111111111111:role/test-euc1-pdev-policy-reporter-sa-iam-service-account-role
  name: "policy-reporter-sa"

extraVolumes:
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "policy-reporter-aws-secrets"
  volumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
````

Could you please help us understand why the policy-reporter pod is failing to assume the correct permissions despite the manually verified credentials?
Is there a possible configuration change needed post-upgrade that we might have missed?
