### ISSUE TITLE
TargetConfig skipTLS and certificate are mandatory?

### ISSUE THREAD

**Issue by agardnerIT** [fjogeleit/policy-reporter#937]
According to [this page](https://kyverno.github.io/policy-reporter-docs/policy-reporter/integrations.html#webhook), `certificate` is `(optional)` and `skipTLS` should default to `false` (if not provided):

But when I attempt to apply this:

```
apiVersion: policyreporter.kyverno.io/v1alpha1
kind: TargetConfig
metadata:
  name: example
spec:
  webhook:
    webhook: 'https://example.com'
    headers:
      'Authorization': 'Api-Token ******'
      'Content-Type': "application/json"
```

I receive:

```
The TargetConfig "example" is invalid: 
* spec.webhook.certificate: Required value
* spec.webhook.skipTLS: Required value
```

So I add `skipTLS` and still get a warning about the certificate: `The TargetConfig "example" is invalid: spec.webhook.certificate: Required value`

```
apiVersion: policyreporter.kyverno.io/v1alpha1
kind: TargetConfig
metadata:
  name: example
spec:
  webhook:
    skipTLS: false
    webhook: 'https://example.com'
    headers:
      'Authorization': 'Api-Token ******'
      'Content-Type': "application/json"
```

![Image](https://github.com/user-attachments/assets/9e2aa3df-e5aa-45a3-9e38-049dcb0676ed)

## Helm List

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kyverno         kyverno         1               2025-05-14 11:36:52.0192452 +1000 AEST  deployed        kyverno-3.4.1           v1.14.1
policy-reporter policy-reporter 3               2025-05-14 13:17:29.6752485 +1000 AEST  deployed        policy-reporter-3.1.3   3.1.1
```
