### ISSUE TITLE
Problem with security of container

### ISSUE THREAD

**Issue by mkatana-silkycoders** [fjogeleit/policy-reporter#987]
## Problem in Two Containers

- `policy-reporter-ui`
- `policy-reporter-kyverno-plugin`

Both applications **require elevated securityContext permissions** to run successfully on OpenShift:

```yaml
securityContext:
  runAsUser: 0
  runAsNonRoot: false
  privileged: true
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  capabilities:
    drop: [ ]
  seccompProfile:
    type: RuntimeDefault
```

Without the following lines:

```yaml
privileged: true
allowPrivilegeEscalation: true
```

the pods get stuck and the application returns the error:

```
Empty reply from server
```

This appears to be caused by **SELinux restrictions**, which block the application from starting correctly.

---

## Tested On

- Helm: `3.1.4`
- `policy-reporter-ui`: `2.3.10`
- `policy-reporter-kyverno-plugin`: `0.4.4`

---

## Default Permissions

- For `policy-reporter-ui`:  
  [policy-reporter/values.yaml#L1107](https://github.com/kyverno/policy-reporter/blob/policy-reporter-3.1.4/charts/policy-reporter/values.yaml#L1107)

- For `policy-reporter-kyverno-plugin`:  
  [policy-reporter/values.yaml#L1320](https://github.com/kyverno/policy-reporter/blob/policy-reporter-3.1.4/charts/policy-reporter/values.yaml#L1320)

---

## Question

Why do these applications require `privileged` and `allowPrivilegeEscalation: true` to function properly on OpenShift?

Why UI require `privileged`???
