### ISSUE TITLE
policyExclude removes policyresults from the UI.

### ISSUE THREAD

**Issue by bartvanackooij** [fjogeleit/policy-reporter#997]
Hi, 

**versions:** 
policy-reporter version: **3.1.1**
deployed through helm chart version: **3.1.4**

Not sure if this is a bug, or as intended, but let's say I expected a different outcome. 

I've got the kyverno-policies deployed in **Audit** mode and podSecurityStandard as **restricted**. So when I go the policy-reporter dashboard, it shows below the PSS Restricted polcies the **'Restrict Volume Types'** with 71 passes, and 2 violations. Awesome, the goal is to fix everything. And the 2 failures are the node-exporter and let's call it pod B. 

![Image](https://github.com/user-attachments/assets/70abc078-8b04-4dce-b119-557ea28eb416)

Now I have a pod that violates this policy, so I've made a policyExclude for the pod in the kyverno-policies helm chart, nothing fancy; 

```
policyExclude:
  restrict-volume-types:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - monitoring
        names:
        - "node-exporter-*"

skipBackgroundRequests: false
```
And this works, I apply it, I trigger a pod creation for the node-exporter, and also for the pod B (that was the second violation), and looking at the events it only shows 

```
Warning   PolicyViolation          pod/pod-B                               policy restrict-volume-types/restricted-volumes fail:
... 
``` 

whereas without the policyExclude, the node-exporter pod would show as well. So the exclusion works and it only hits the intended pods. 

So far so good. 

But now, when I look at the dashboard, it shows: 

![Image](https://github.com/user-attachments/assets/eabf835e-9cdc-4d04-8a68-19a5c3d9e042)

0 pass, 0 failures. 
Where I would expect to see ~70 passes, 1 failures.  (pod B)

From what I understood the policy-reporter uses the reports from kyverno for it's data. So I removed all policyreports for node-exporter and for pod B. 

For node-exporter, the restrict-volume-types is not present as expected. 

pod B: 

```
❯ k get polr -n monitoring 461e...03f -o yaml | grep -A 3 restrict-volume-types
  policy: restrict-volume-types
  properties:
    process: background scan
  result: fail
```
Other policyreports are present as well, showing `result: pass` which aren't reflected in the UI as well. 

I've restarted everything,  I don't see any errors in de logs. What am I missing here?
